### ISSUE TITLE
Consider using the Intersection Observer API

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#114]
Chrome 51 comes with the new Intersection Observer API to track if elements are visible or invisible in the viewport. So far it is only supported in Chrome, but other browser might follow, due to the W3C standard.
- Blog Post - https://goo.gl/NyF7Z0
- Demo - https://goo.gl/37Yi0V
- WICG Spec Repo - https://goo.gl/CkokY6
- WICG Spec - https://goo.gl/rwKUcb
- Chrome Status - https://goo.gl/8ZNpvm

**Comment by sgratzl** [comment]
polfill.io https://polyfill.io/v2/docs/features/#IntersectionObserver
