### ISSUE TITLE
Deploy Lineup.js releases on S3

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#125]

**Comment by sgratzl** [comment]
what is the purpose, why is

https://raw.githubusercontent.com/Caleydo/lineup.js/v0.5.2/dist/LineUpJS_bundle.min.js

with https://rawgit.com/

-->

https://cdn.rawgit.com/Caleydo/lineup.js/v0.5.2/dist/LineUpJS_bundle.min.js

not enough?

**Comment by sgratzl** [comment]
see http://lineup-releases.s3-website.eu-central-1.amazonaws.com/latest/LineUpJS.js
