### ISSUE TITLE
Custom Cell Render

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/lineupjs#145]
In https://github.com/sgratzl/lineup_custom_renderer @sgratzl implemented a first version of a box plot cell renderer as well as a shape cell renderer. In addition, it would be useful to create custom renderers such as:
- Heat map
- Spark line
- Bar chart
- Box plot with median (initial version exists already)
- Temporal line chart (Filter dialog selects time point that is taken for ranking).

**Comment by mstreit** [comment]
I've updated @bikramkawan's description above. Bikram will take care of creating those additional cell renderers. @sgratzl, please support him with this. He already started to play with a heatmap cell renderer.

**Comment by sgratzl** [comment]
please don't forget to work in a separate branch

**Comment by bikramkawan** [comment]
I have pushed work so far I have done in the brach 'bikram-customcellrenderer'. I have some question regarding the implementation of custom renderer.

So far I have made custom renderer for heat map, sparkline and boxplot. I have used dummy data for now and the output looks as here.
![image](https://cloud.githubusercontent.com/assets/12292333/19691721/7cbdfedc-9ad5-11e6-85c5-83cbf76e920c.png)

I am confused on how to gather information from Column A and Column C to generate heat map or other renderers. What will be the data structure needed to generate custom renderer.

**Comment by mstreit** [comment]
@sgratz:l is it already possible that one custom cell renderer takes the data from multiple columns in the data model (such as C and A in the example shown above).

a heat map is actually not much different from a combined column that shows a stacked bar, which would be just a different representation of the same data (multiple columns). so in the end we could have multiple types of combined columns: stacked bar, heatmap, sparkline, box plot. all of them take the data from multiple columns.

**Comment by sgratzl** [comment]
I don't get it. 

You are suggesting a datastructure like: 
```
{
  name: 'test', 
  v1: 3,
  v2: 1,
  v3: 4,
  v4: 5,
  v...
  v100: 4,
  other: 1000
}
```

where each column is defined independently, having its own type, definition, and so on. So, a heatmap / sparkline / ... could be combined with any other number column, (e.g., `other`) from a different context. 

What are the advantages compared to: 

```
{
  name: 'test', 
  v: [3, 1, 4, 5, ..., 4],
  other: 1000
}
```
which introduces a multi value column that can be visualized using a spark line, heatmap, boxplot?

**Comment by mstreit** [comment]
yes, that is what I would expect, too. is that also the way how combined stacked columns are defined?

**Comment by sgratzl** [comment]
Currently everything is based on the first datastructure. A combined columns is a composite of other columns. In the stacked bar case, each columns has its own mapping, column, ... So, they are heterogeneous. 

However, in a sparkline case, each "member" should be of the same type, have the same domain, have the same meaning. Otherwise stitching them together has no meaning at all.

**Comment by bikramkawan** [comment]
I have replace the constant numbers by some random data points. 
The data structure for each row looks like below:
  ```
{
      a: 10,
      b: 20,
      c: 30,
      d: 'Row1',
      cat: 'c1',
      custom: {min: 10, max: 100, mean: 30},
      heatmapcustom: heatmapdata(6, 1, 30),
      sparklinecustom: getrandom(100, 1, 10),
      boxplotcustom: boxdata(60, 1, 100)

    }
```
Now the heatmapcustom contains the random array of number so as for sparkline and box plot. 
For example heaptmapdata(6,1,30) will generate 6 numbers which are in range of 1 and 30.
For box plot i have calculated five numbers  mean, median, q1,q3 and max. 
Now it looks like.
![image](https://cloud.githubusercontent.com/assets/12292333/19772909/f8b6b77a-9c67-11e6-9be6-dbed1ed4afb0.png)

**Comment by bikramkawan** [comment]
Update:
![image](https://cloud.githubusercontent.com/assets/12292333/20065960/3f491f56-a510-11e6-9a49-441fcd36b470.png)

**Comment by bikramkawan** [comment]
Update: I have added the User Sorting criteria. Please comment if this is good way to represent or not .
![image](https://cloud.githubusercontent.com/assets/12292333/20301673/8ccb14f4-ab24-11e6-99e9-d83eb70d0577.png)

**Comment by mstreit** [comment]
Looks fine for the first iteration.
