### ISSUE TITLE
Let user specify sorting criterion for columns that contain an array of values

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#150]
For heatmap, vertical bar chart, and sparkline cell renderers ( #145), the UI should allow the user to define that the ranking criterion is. By default, we could rank by average or median. But also other criteria such as min and max should be possible.

Issues to think about:
- Think about multiple instances of a column or multiple lineups on the same page (i.e., comparative setup).
- Should therefore not be part of the main library but rather implemented as a hook. 
- Should be part of the config/dump

**Comment by bikramkawan** [comment]
Prototype:
![image](https://cloud.githubusercontent.com/assets/12292333/20747745/8dd4160c-b6eb-11e6-9591-66521135e111.png)
