### ISSUE TITLE
Histograms include NaN values

### ISSUE THREAD

**Issue by pkerpedjiev** [Caleydo/lineupjs#166]
Example input file:

https://drive.google.com/open?id=0B2amcfXKOyc3YVd5ejV5Z1pOVUU

The histograms on top of each column look slightly off:

![image](https://cloud.githubusercontent.com/assets/2143629/20267927/e59f54bc-aa4a-11e6-8f65-7c5abddf38ff.png)

Is that how they should look or are they including the NaN values as well?

**Comment by sgratzl** [comment]
missing values are internally mapped to a configurable `missingValue` number. By default this is `0`.

**Comment by mstreit** [comment]
Hm, mapping it to 0 is actually wrong because it adds data that is not defined in the dataset. Can we set `missingValue` to `NaN` which is ignored by the histogram? The clean solution would be to add an additional bar for NaN to the histogram that has a different style (maybe a grey background?).

**Comment by pkerpedjiev** [comment]
Could `missingValueNumber` be set to `Nan`? What about other data sets
where the domain is not [0, X]?

**Comment by sgratzl** [comment]
still valid?

**Comment by mstreit** [comment]
Missing values are not included in the histogram anymore, right? If this is the case, this issue is resolved.
