### ISSUE TITLE
Column header histogram of aggregation column not shown

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#174]
When adding a stack column, the column header does not contain the histogram of all values. However, it appears after sorting the column.

**Comment by sgratzl** [comment]
histograms are currently just possible for plain numerical and categorical columns.

**Comment by thinkh** [comment]
@sgratzl Is this still valid with the new lineupengine?

**Comment by thinkh** [comment]
Histogram for stacked columns are not available (also after sorting).

![image](https://user-images.githubusercontent.com/5851088/49028017-be53ed00-f1a1-11e8-9be9-1c0fc03dd50e.png)
