### ISSUE TITLE
Rows are flickering when scrolling vertically using the HTML renderer

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#180]
When using the HTML renderer and scrolling vertically the whole LineUp rows are repositioned from the origin (0,0), which results in a flickering.

![html-renderer-issue](https://cloud.githubusercontent.com/assets/5851088/20555852/61450b6e-b164-11e6-9510-c12e9ca62c0d.gif)

Tested with the LineUp `release_1.x` branch.

**Expected**
The rows should stay stable on scrolling (as they do with the other renderers).

**Comment by sgratzl** [comment]
as far as I remember the issue is that d3 v3 can't animate the `css-transform` property properly.

**Comment by sgratzl** [comment]
todo test at d3 v4 branch
