### ISSUE TITLE
migrate branch bikram-customcellrenderer to latest release_1.x code

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#184]
main changes
 * code split up: ui.ts, model.ts, ... are split up in individual files
 * renderer changes: the whole rendering logic has changed, see e.g., new default renderer for svg (https://github.com/Caleydo/lineup.js/blob/release_1.x/src/renderer.ts#L109)

**Comment by bikramkawan** [comment]
Migrated to SVG and Canvas but html renderer is still remaining.

**Comment by mstreit** [comment]
What is the status here?
