### ISSUE TITLE
create BoxPlotColumn

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#198]
similar to a multi value column but the values are already the box plot data. 

additional box plot information
 * length
 * avg

visualizations: 
 * box plot
 * [bar with wiskers] - bar length: avg or median, wiskers: min/max or q1/q3?
 * bar - depending on sorting criteria: median, q1, q2, min, max, avg

**Comment by mstreit** [comment]
https://github.com/Caleydo/lineupjs/pull/187
