### ISSUE TITLE
MultiValue Changing Sort Criteria changes the heatmap representation

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#210]
* Release number or git hash: 30c120141c03f51ee53661e446249bec3e83bc71
* Web browser version and OS: local

### Steps to reproduce

1. e.g. filter to all having `ec` in the name,
1. switch to Heatmap representation
1. observe heatmap representation of Ecuador
1. change sorting criteria of the column, to median, q1, q3

### Observed behavior
the heatmap changes of Ecuador

![test](https://cloud.githubusercontent.com/assets/4129778/21685645/a392f3c6-d362-11e6-8a5d-c633e7315532.gif)

### Expected behavior
* heatmap doesn't change representation

**Comment by bikramkawan** [comment]
I checked in the console and color coding is same
![image](https://cloud.githubusercontent.com/assets/12292333/21687125/577d8f90-d368-11e6-85aa-6716b83dc00c.png)
