### ISSUE TITLE
create htmlwidget wrapper

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#224]
see http://www.htmlwidgets.org/

**Comment by timelyportfolio** [comment]
Happy to help if I can.

**Comment by sgratzl** [comment]
I started a new repository: https://github.com/caleydo/lineupjs_htmlwidget. You are welcome to contribute, especially
 * how to input a data frame and extract meta data out of it (column types)
 * convert data frame to json structure

**Comment by timelyportfolio** [comment]
I did some experiments with the first version of lineupjs.  I'll try to dig up those since I remember writing some crude conversions.

**Comment by sgratzl** [comment]
I implemented a first version at https://github.com/Caleydo/lineup_htmlwidget

![2017-01-23 16_59_48-rstudio](https://cloud.githubusercontent.com/assets/4129778/22211811/9cd10ebc-e18e-11e6-9f76-5a9f24c4e79a.png)
![2017-01-23 17_00_07-rstudio](https://cloud.githubusercontent.com/assets/4129778/22211814/9ee17098-e18e-11e6-8a65-2fa1ea22d035.png)

**Comment by timelyportfolio** [comment]
very nice!  head now spinning with ideas.
