### ISSUE TITLE
create bar with wiskers renderer

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#230]
e.g. as an alternative to the boxplot renderer

bar length -> median
wiskers -> q1, q3?

**Comment by mstreit** [comment]
why do we want to have this? if we summarize a distribution of items, it should always be shown as a box plot.

**Comment by mstreit** [comment]
OK, but why shouldn't we use box plots in this case? we should also educate our users.

**Comment by mstreit** [comment]
see http://www.nature.com/nmeth/journal/v11/n2/abs/nmeth.2807.html
