### ISSUE TITLE
support row grouping and collapse

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#242]
e.g., similar to Microsoft Excel Group Feature: http://www.wikihow.com/Group-and-Outline-Excel-Data

**Comment by mstreit** [comment]
Just to clarify this: such composite columns would allow us to aggregated the data. We could even show different visualizations for aggregated cells (boxplot, histogram, etc.).

**Comment by mstreit** [comment]
Just to clarify this: such composite columns would allow us to aggregate multiple rows into a single row. We could then also show different visualizations for aggregated cells (boxplot, histogram, etc.).

**Comment by sgratzl** [comment]
see also #220

**Comment by sgratzl** [comment]
see grouping branch

![greenshot_2017-06-30_16-43-07](https://user-images.githubusercontent.com/4129778/27742546-6d447722-5db9-11e7-9329-a5f1563f46a2.png)
