### ISSUE TITLE
implement brushed selection

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#246]
such that user can drag and select multiple items. could be restricted to the selection column only

**Comment by mstreit** [comment]
I'm setting this to high because it's also important for Taggle.

**Comment by sgratzl** [comment]
![brush](https://user-images.githubusercontent.com/4129778/31434467-c293b166-ae7c-11e7-9460-5199b602ed42.gif)

**Comment by thinkh** [comment]
@sgratzl does the brush only on string columns or all column types?

**Comment by sgratzl** [comment]
![gif](https://user-images.githubusercontent.com/4129778/31437452-9bc7901c-ae85-11e7-8864-a22062411bdc.gif)

**Comment by mstreit** [comment]
nice. @thinkh, I think it would be good to also turn off the text highlights as part of your style changes.

**Comment by thinkh** [comment]
Thanks. Very nice. 👍

**Comment by sgratzl** [comment]
> nice. @thinkh, I think it would be good to also turn off the text highlights as part of your style changes.

then you cannot copy a line anymore.

**Comment by mstreit** [comment]
cannot we just change the style to not change but still select the text when copying? how is this handled in other visualizations?
