### ISSUE TITLE
nesting a stacked column in a stacked column restults in a header mess

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#255]
* Release number or git hash: latest
* Web browser version and OS: windows, chrome

### Steps to reproduce

1. create two combined columns and nest one in the other

### Observed behavior
* the header of the nested column is messed up 

![2017-05-31 08_42_32-lineup - lineup - urank](https://cloud.githubusercontent.com/assets/4129778/26619105/46311cba-45dd-11e7-983d-136826005640.png)

**Comment by thinkh** [comment]
This is fixed with the current LineUp v4.0.0-alpha.8.

![image](https://user-images.githubusercontent.com/5851088/49028255-433f0680-f1a2-11e8-9238-a976fef11a51.png)
