### ISSUE TITLE
define and test supported browsers

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#259]
goal: 
 * current Chrome
 * recent ESR of Firefox
 * Edge
 * Safari?

e.g. with https://www.browserstack.com/

**Comment by sgratzl** [comment]
edge issues: 
 * svg: text clippath not working as expected
 * svg: dominant-baseline not supported (https://msdn.microsoft.com/en-us/library/gg558060(v=vs.85).aspx)
 * all: scroll/smooth results in low update frequencies

firefox issues: 
 * all: scroll/smooth results in low update frequencies

**Comment by sgratzl** [comment]
see also #263 and https://codepen.io/sgratzl/pen/VWqJQq?editors=0110

## edge issues
 * frozen columns are working but are manually, due to missing support of `position: sticky`. results in visual glitches
 * same for the slopegraph in vertical direction.

**Comment by thinkh** [comment]
Done see https://lineup.js.org/about#supported-browsers.
