### ISSUE TITLE
ideas for an icon?

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#275]
e.g. that could be used for loading, processing + in lineup apps

**Comment by mstreit** [comment]
how about this http://fontawesome.io/icon/signal/ rotated and flipped? @thinkh or @alexsb, any other ideas?

**Comment by alexsb** [comment]
The purpose here is a loading icon?

**Comment by thinkh** [comment]
@sgratzl should the loading icon overlay the whole app (similar to the Caleydo icon) or is it considered for cell render?

**Comment by sgratzl** [comment]
I wanted an icon for lineup as we have it for taco, thermalplot, ...

**Comment by mstreit** [comment]
Yes, but for what purpose? If we need an icon for a ranking view, let's use something generic that describes a ranked list:
https://fontawesome.com/icons/list-ol?style=solid
https://fontawesome.com/icons/signal?style=solid (mirrored and rotated by 90)
