### ISSUE TITLE
support ranking buttons

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#308]

**Comment by mstreit** [comment]
what is this issue about?

**Comment by sgratzl** [comment]
![greenshot_2017-09-22_15-39-38](https://user-images.githubusercontent.com/4129778/30747085-69dbcbb4-9fac-11e7-9f3e-7d9357a29954.png)

**Comment by mstreit** [comment]
@sgratzl, is this fixed with the Taggle side panel?
