### ISSUE TITLE
bug: combining two numerical columns results in empty cells

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#314]
**Description**
![image](https://user-images.githubusercontent.com/4129755/30514386-0c8ca9ac-9b14-11e7-9438-4cbbe21ff289.png)

**Steps to reproduce**
1. stack two numerical columns

**Supposed behavior**

**Comment by mstreit** [comment]
Works now as expected:
![image](https://user-images.githubusercontent.com/4129755/30590166-cc1ec536-9d3d-11e7-9f99-139e1dc07f9c.png)
