### ISSUE TITLE
ignore NaN values for the aggregation?

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#319]
Aggregating a numerical group with at least one NaN will result in a NaN value. Should we ignore NaN values for the aggregation?

**Comment by mstreit** [comment]
Yes, I think so.

**Comment by sgratzl** [comment]
> Yes, I think so.

you are answering your own question, since I just moved the issue created by you :D

**Comment by mstreit** [comment]
ah good, at least the answer was consistent with my suggestion ;)
