### ISSUE TITLE
Better drag'n'drop for side panel

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#322]
At the moment the drag and drop for the side panel is a bit difficult to use, due to the small drop areas.

This article provides a better solution how to improve the d'n'd experience: https://medium.com/@alexandereardon/rethinking-drag-and-drop-d9f5770b4e6b

This is the repository (based on react): https://github.com/atlassian/react-beautiful-dnd

**Comment by sgratzl** [comment]
does it work with native dnd?

**Comment by mstreit** [comment]
I think the DnD in the Taggle 1 side panel worked very well.

**Comment by sgratzl** [comment]
I'm not going to add JQuery and JQuery-UI as dependencies to lineup.

**Comment by mstreit** [comment]
ok
