### ISSUE TITLE
Change alternating background pattern to row border-bottom lines

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#325]
Instead of the _zebra_

![grafik](https://user-images.githubusercontent.com/5851088/30653412-4c9b4c78-9e2b-11e7-9a66-c8e6c57e5bef.png)

we want something like this

![grafik](https://user-images.githubusercontent.com/5851088/30653559-b1b6bd18-9e2b-11e7-9ea2-4e59262f2f18.png)

**Comment by mstreit** [comment]
Looks good!

**Comment by sgratzl** [comment]
isn't that part of the engine?

**Comment by thinkh** [comment]
We decided to remove the border at all and only show the border for hover and selected rows.

![image](https://user-images.githubusercontent.com/5851088/30698635-d51a091a-9ee2-11e7-87f6-b55b2e8f33e0.png)
