### ISSUE TITLE
change missing values encoding from hatching pattern to centered dash

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#326]
The dash has the big advantage that it also works in overview mode.

**Comment by thinkh** [comment]
High LOD:

![image](https://user-images.githubusercontent.com/5851088/30687217-ec41ba98-9eba-11e7-8af8-d7fd55958721.png)

Medium LOD:

![image](https://user-images.githubusercontent.com/5851088/30687256-090ad93e-9ebb-11e7-86cd-e1fac0379427.png)

Low LOD:

![image](https://user-images.githubusercontent.com/5851088/30687298-2000eef8-9ebb-11e7-8507-4e49d51e3cab.png)

**Comment by mstreit** [comment]
very nice, much better than the hatching.
