### ISSUE TITLE
Hide icons if column is too narrow (show only more icon)

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#336]
Icons overflow when column is too narrow: 

![image](https://user-images.githubusercontent.com/2039375/30754745-2fe7a610-9f81-11e7-94df-09e97e939c0c.png)

Solution: remove all but the "more" icon, add the other menu items to the "more" menu. Enforce a minimum width of N pixel, N~20?

**Comment by sgratzl** [comment]
you cannot enforce a minimum width in general, since in a stacked bar, you cannot enforce a minimal weight = column width

**Comment by mstreit** [comment]
ok, but we could enforce the minimum width for non-stacked columns.

**Comment by thinkh** [comment]
Done with #333.

![image](https://user-images.githubusercontent.com/5851088/31550982-6fc64e18-b033-11e7-991f-dfc311ee5b33.png)

Re-open if necessary.
