### ISSUE TITLE
Integrate the visualization menu with the top-level menu ?

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#338]
Maybe integrate the visualization menu with the top-level menu? 

![image](https://user-images.githubusercontent.com/2039375/30754815-7833770a-9f81-11e7-9108-7a9815cb3e1d.png)

The nesting seems not necessary.

**Comment by thinkh** [comment]
I would not do that.

@sgratzl @mstreit @alexsb Your opinions please.

**Comment by mstreit** [comment]
Yes, let's leave it as it is.
