### ISSUE TITLE
Disable sorting by click on header

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#339]
Now that we have an explicit sorting icon, remove sorting by clicking on the header

**Comment by mstreit** [comment]
As multiple people mentioned this already, this interaction is obviously not the best and can be removed.

**Comment by thinkh** [comment]
@sgratzl What is the reason that you put this issue into the backlog. Is this difficult to disable/implement?

**Comment by thinkh** [comment]
Disabled the sorting when clicking the header. The hand cursor is still shown to indicate that the column can be moved.

![disable-sorting](https://user-images.githubusercontent.com/5851088/31611178-52b76f7e-b27b-11e7-808c-0b695ccb564f.gif)

Part of PR #333.
