### ISSUE TITLE
Better popup position

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#340]
Issues with popup position:
* popups in the side panel should open to the left (and not to the right)
* popups are not sticky, i.e. when scrolling they don't move too

@sgratzl Instead of implementing all this behavior everything ourself, I'd prefer to use a library like [tippy.js](https://atomiks.github.io/tippyjs/) or [tooltip.js](https://github.com/FezVrasta/popper.js#tooltipjs) (both are based on [popper.js](https://github.com/FezVrasta/popper.js)), that handle these issues already. Is it ok for you to add one of these libraries as dependency?

P.S. We could also use them for nicer tooltips later

**Comment by sgratzl** [comment]
popper.js looks interesting, especially since it has no dependencies. 
tippy.js is for me too much magic and my override behavior by applications that use lineup as a library.

**Comment by thinkh** [comment]
Close issue, because PR is merged. Open another issue for further bugs and feature requests.
