### ISSUE TITLE
Remove spacing for histogram when column is narrow

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#341]
Remove spacing for histogram when column is narrow: 

![image](https://user-images.githubusercontent.com/2039375/30754917-df2a323c-9f81-11e7-9c01-f2a4247d61ba.png)

**Comment by thinkh** [comment]
Difficult to define, since this depends on the number of bars/bins and the available width. That needs some JS, which sets a CSS class when changing the column width.

**Comment by thinkh** [comment]
This might be helpful: http://kizu.ru/en/blog/flexible-overflow/

**Comment by thinkh** [comment]
The [ResizeObserver](https://developers.google.com/web/updates/2016/10/resizeobserver) could be also helpful for this task. It will be shipped in the upcoming [Chrome 64](https://blog.chromium.org/2017/12/chrome-64-beta-stronger-pop-up-blocker_14.html).

**Comment by thinkh** [comment]
Another source of inspiration https://css-tricks.com/container-adapting-tabs-with-more-button/

**Comment by mstreit** [comment]
won't fix
