### ISSUE TITLE
Add an axis to the header for numerical columns

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#342]
Add an axis to the header for numerical columns. Something like this: 

![image](https://user-images.githubusercontent.com/2039375/30755462-faf3c9a4-9f83-11e7-8d0c-8a1de0e2967d.png)

**Comment by mstreit** [comment]
I change the priority because I think it's critical for users and also for our paper.

**Comment by thinkh** [comment]
Needs further specification where to place the scale.

**Comment by sgratzl** [comment]
![2017-11-10 10_34_36-taggle - aids](https://user-images.githubusercontent.com/4129778/32651900-c6118596-c602-11e7-8c4a-80f0bd337ca5.png)

-> move label below the histogram --> requires that the header is higher and the other histograms need to be aligned
