### ISSUE TITLE
Allow to define order for sorting of categorical values

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#345]
Right now, categories are sorted alphanumerically. Instead, I'd like to be able to change the sorting by interacting with the histogram.

Of course, the histogram sorting would only work if the column is sorted by.

**Comment by mstreit** [comment]
related to #330

**Comment by mstreit** [comment]
this is also very relevant for the chromosome column in ordino. changing priority to high.

**Comment by mstreit** [comment]
works now with Taggle (without sorting it).

![image](https://user-images.githubusercontent.com/4129755/34864143-210b22ee-f773-11e7-8daf-648e4aa547a4.png)
