### ISSUE TITLE
improve scripted column

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#347]
the help and editor needs some 'attention'

![image](https://user-images.githubusercontent.com/5851088/31539645-7ec595f6-b009-11e7-932f-19fbdf07cbf1.png)

**Comment by thinkh** [comment]
[xcell](https://tomazy.github.io/xcell/) provides an idea how scripted cells similar to a spreadsheet can work. Maybe we can adapt the LineUp implementation and provide a better usability providing suggestions while typing.

**Comment by thinkh** [comment]
In LineUp v4.0.0-alpha.8 the whole help text is gone. 

![image](https://user-images.githubusercontent.com/5851088/49029141-36231700-f1a4-11e8-9bcf-ce443a34a6d3.png)

Though I opened a new issue to improve the scripted column -> https://github.com/datavisyn/lineupjs/issues/116
