### ISSUE TITLE
scripted column: reference column by name

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#349]
currently the columns can only be accessed through the `values` array. However, to improve readability, access via name would be useful. 

such as 

`(col.a + col.b)/2`

currently just: `(values[0] + values[1]) /2`

issues: how to identify columns easily? -> label of the column, can be changed and possible very long

**Comment by thinkh** [comment]
Moved/integrated into https://github.com/datavisyn/lineupjs/issues/116
