### ISSUE TITLE
File | Load Data menu is inactive after installing macOS high sierra 

### ISSUE THREAD

**Issue by gurol** [Caleydo/lineupjs#352]
I could not load my custom data that I used to load, after upgrading my OS into the new version (macOS high sierra). The File | Load Data menu is alwats disabled. Although, the demo is loaded at startup. Thanks.

<img width="806" alt="resim" src="https://user-images.githubusercontent.com/14318443/31137427-ed613756-a873-11e7-85ca-ed53b8f08bb1.png">

**Comment by mstreit** [comment]
Thanks for letting us know. This repo contains the code of the LineUp JavaScript library (Demo: http://lineup.caleydoapp.org). You are working with the discontinued Java version.

**Comment by sgratzl** [comment]
you can also upload your own CSV in the lineup JavaScript version at https://lineup.caleydoapp.org

![2017-10-03 19_07_49-lineup - legatum prosperity index](https://user-images.githubusercontent.com/4129778/31138313-51fd9124-a86e-11e7-9bc3-d1d099a06ba9.png)

**Comment by gurol** [comment]
Thank you for your help @mstreit and @sgratzl
