### ISSUE TITLE
Improvements for slope graphs and bands

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#353]
With https://github.com/Caleydo/lineupjs/issues/307#issuecomment-333880025 @sgratzl (re-)introduced the bands and slope graphs to the new LineUp renderer. 

Here are some ideas how we could discuss/improve:

1. When stratifying a column we should switch to bands instead of individual slope graphs
2. Show lines in bands similar to [Matchmaker](https://www.youtube.com/watch?v=vi-G3LqHFZA)
3. Show bands and when hovering with the mouse switch to slope graphs
4. Let the user switch between band or slope visualization (similar as we do it for columns)

**Comment by mstreit** [comment]
Having this would be really nice for Taggle. But it's not a must have.

**Comment by sgratzl** [comment]
if it is not a must, why then high priority?

**Comment by sgratzl** [comment]
![2017-12-27 16_55_43-start](https://user-images.githubusercontent.com/4129778/34386030-e1b6b782-eb26-11e7-8079-2392d885de27.png)
![2017-12-27 16_55_46-taggle - aids](https://user-images.githubusercontent.com/4129778/34386031-e1d0c37a-eb26-11e7-876c-43e119183c9f.png)

**Comment by thinkh** [comment]
@sgratzl Very nice 👍

**Comment by mstreit** [comment]
Indeed!

**Comment by thinkh** [comment]
Closed via PR #500
