### ISSUE TITLE
Add aggregate visualizations for matrix

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#354]
At the moment there are no aggregated visualizations available for matrices.
![image](https://user-images.githubusercontent.com/4129755/31201394-5dae9ef0-a913-11e7-90b9-a7db386ad661.png)

We need the following aggregate visualizations for the matrix:
- (1D) heatmap
- boxplot (based on the 1D heatmap aggregated values)

**Comment by sgratzl** [comment]
a heatmap showing which aggregation?

**Comment by sgratzl** [comment]
> boxplot (based on the 1D heatmap aggregated values)

why based on the 1D aggregation?

**Comment by mstreit** [comment]
re heatmap aggregation: the aggregated columns (as we join columns, this is what I would expect as a user)

**Comment by sgratzl** [comment]
still which aggregation method, I got the in column direction part? mean, median, min, max, ...

**Comment by mstreit** [comment]
ideally the user should be able to choose the aggregation method. for now, just pick one (mean or median).

**Comment by mstreit** [comment]
we already offer multiple aggregation methods by offering "avg bar' 'median bar'.
