### ISSUE TITLE
aggregates not updated when changing filters

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#359]
### Steps to reproduce

1. aggregate by some categorical attribute
2. filter out many items

### Observed behavior
* aggregates (e.g., box plot) are not updated after filter operation

### Expected behavior
* properly updated aggregated visualizations

**Comment by sgratzl** [comment]
cannot reproduce in lineup with the lineup row management: 

![gif](https://user-images.githubusercontent.com/4129778/31427697-71496a12-ae68-11e7-9a64-97f003158a8e.gif)
