### ISSUE TITLE
Remove/hide `color` renderer for categorical items from visualization selection

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#367]
![image](https://user-images.githubusercontent.com/5851088/31538353-93eb8638-b005-11e7-9cea-480dc742e737.png)

Rename: `Color + Label` to `Color`

**Comment by sgratzl** [comment]
why?

**Comment by thinkh** [comment]
Because in a high level of detail colored blocks only (without labels as you see them in the screenshot) does not make sense. The behavior of `Color + Label` is sufficient (i.e. high LOD = color + label; low LOD = colored blocks).

**Comment by sgratzl** [comment]
lineupjs has no notion of level of detail + if the column is narrow is does make sense imo to just show the color

**Comment by mstreit** [comment]
addressed as part of #401.
![image](https://user-images.githubusercontent.com/4129755/31945068-65425dee-b8ce-11e7-9938-7f48b86d24f1.png)
