### ISSUE TITLE
Manipulating the width of stratified matrix collapses sub-columns

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#371]
**Reproduce**

1. Stratify a matrix column
2. Manipulate the width of the matrix column using drag'n'drop
3. All sub columns are collapsed

![stratified-matrix-columns](https://user-images.githubusercontent.com/5851088/31539401-be31ca6c-b008-11e7-83bc-af2b9e074b47.gif)

**Expected**
Manipulating the width of a stratified matrix column should should distribute the width of the sub-columns equally (and not collapse them).

**Comment by sgratzl** [comment]
is it true for the develop branch, too?

**Comment by thinkh** [comment]
Yes, it also happens in the current lineupjs develop branch.

![image](https://user-images.githubusercontent.com/5851088/31540128-0d3f8192-b00b-11e7-98a1-0efcae6b5e61.png)

**Comment by sgratzl** [comment]
part of https://github.com/Caleydo/lineupjs/commit/a44b093a164c8c162c00a0bad27cbabe6fb92aef
