### ISSUE TITLE
changing the color on a categorical column causes crash

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#378]
* Release number or git hash: master
* Web browser version and OS: chrome

### Steps to reproduce
1. change color for a categorical column

### Observed behavior
* browser freezes 

### Expected behavior
* changing the color of the bars

**Comment by sgratzl** [comment]
don't get it. how should changing the color of a categorical column (Rename + Color) should have an affect on all the categories?

**Comment by mstreit** [comment]
The 'Rename + color' dialog shows properly. When I click the gray color, the color picker dialog opens, which causes my browser to crash completely (not just the tab).

**Comment by thinkh** [comment]
But this might be a OS X problem!? @mstreit  Did you update your browser or OS X recently?

**Comment by mstreit** [comment]
yes, I did. I can test again after the next update.

**Comment by mstreit** [comment]
the issue is valid! it's probably not just my machine but affects all MacOSX systems.
@alexsb, can you please test it?

**Comment by mstreit** [comment]
I does not crash under Firefox, but changing the color in the picker has no effect. @thinkh, does it work in your Firefox?

**Comment by thinkh** [comment]
The color picker works for me with Firefox 57 and Chrome 62. However, the color is not set afterwards nor visible anywhere. Probably picking a color doesn't make sense for categorical columns? Because you can't pick colors for the categories and we don't show the selected color in the header anymore.

**Comment by alexsb** [comment]
This crashes horribly! Not only the chrome browser, but I had to do a hard restart on the OS.

**Comment by sgratzl** [comment]
see also http://www.xrite.com/service-support/colorpickercrashonmacosxelcapitan1011

**Comment by alexsb** [comment]
Yes, I figured. I think this is a wontfix.
