### ISSUE TITLE
Center checkbox / improve padding

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#379]
Right now selection checkboxes are off-center in single-line mode: 

![image](https://user-images.githubusercontent.com/2039375/31677054-d0f25c86-b326-11e7-8197-58db2f7fd838.png)

That looks a little weird. I'd balance the spacing. I'd not do a real centering, because for groups we do want them at the top.

**Comment by thinkh** [comment]
Done.

![grafik](https://user-images.githubusercontent.com/5851088/31678220-b834ca34-b36d-11e7-8800-b7aa6270b19e.png)
