### ISSUE TITLE
Make sorted by bar orange

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#380]
Right now the sort-by indicator is red, but the sort icon is orange: 

![image](https://user-images.githubusercontent.com/2039375/31677185-37994e2c-b327-11e7-9ce9-6d09899c9658.png)

Make the sort-by indicator in the box plot the same orange too.

**Comment by thinkh** [comment]
Done.

![grafik](https://user-images.githubusercontent.com/5851088/31678051-2d3c4efc-b36d-11e7-8778-0256b376cc17.png)
