### ISSUE TITLE
Labels / Axis? for matrices

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#381]
Right now the matrices don't have any labels for the columns: 

![image](https://user-images.githubusercontent.com/2039375/31677447-102615b8-b328-11e7-964c-021528a05fa7.png)

This is problematic - I can't read off the chart what the years actually are. 

There are two approaches to solving this: 

 * labels for each column, if possible
 * if we have something like years which is continuous, we could show axis or labels only for the first and last one

However, this is even more problematic for larger matrices that don't have any order semantics, such as patients. How do we want to show identifiers there?

**Comment by sgratzl** [comment]
cheap solution for now: add labels to description and show in the summary the first & last label, similar to #342

**Comment by sgratzl** [comment]
part of lineup app since matrix specific: 

![image](https://user-images.githubusercontent.com/4129778/32656683-38c309ce-c613-11e7-96e6-69eed4dd8d1c.png)
