### ISSUE TITLE
Replace aggregate name in string columns with a list of examples

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#384]
Right now, when we stratify by continent: 

![image](https://user-images.githubusercontent.com/2039375/31678069-2f41baa4-b32a-11e7-8ce8-6f5b3713e3d2.png)

We see "Africa (50)" in the list of AIDS_Countries, which is also shown in the "Continent" column. 

I would replace this with a list of examples from that group, i.e., "Algeria, Angola, Benin, Botswana..." for African countries.

**Comment by sgratzl** [comment]
see DefaultCellrenderer -> createGroupDOM & createGroupCanvas

**Comment by sgratzl** [comment]
cornercase stratify by numerical, stratify by selection:
![2017-11-10 10_50_35-taggle - aids](https://user-images.githubusercontent.com/4129778/32652609-13922c88-c605-11e7-9ebe-0cc83cd0b5de.png)

keep group name + add 3 examples from group in second line
