### ISSUE TITLE
Replace red-green color map with red-blue colormap

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#385]
We use a red-green colormap for ordinal data: 
![image](https://user-images.githubusercontent.com/2039375/31678160-7c05d0f0-b32a-11e7-9413-f9bb252dee0e.png)

There is no good reason to use this color map. It opens us up to criticism as it's problematic for red-green colorblind users. Replace with red-blue colormap.

**Comment by sgratzl** [comment]
Issue moved to [Caleydo/taggle #137](https://github.com/Caleydo/taggle/issues/137) via [**ZenHub**](https://www.zenhub.com/)
