### ISSUE TITLE
Remove bar chart as permissible representation for aggregates

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#386]
Bar charts are not suitable to represent the median of a distribution due to within-the bar bias. Remove this option (add a dot plot instead, will create a separate ticket). 

Here is an example for the matrix: 

![image](https://user-images.githubusercontent.com/2039375/31678260-d99981da-b32a-11e7-9f2d-82a94fb0e9a7.png)

Here is an example for a group of a numerical column: 

![image](https://user-images.githubusercontent.com/2039375/31678286-f1f00f24-b32a-11e7-84be-c8afd46c6047.png)

**Comment by sgratzl** [comment]
depends how you see it. if it should a representation of an array I agree, if it should be an representation of a projection of an array to a single value, I disagree.

**Comment by mstreit** [comment]
@sgratzl, I don't understand what you mean. What is your suggestion?

**Comment by sgratzl** [comment]
I mean it is our decision how you wanna see and sell it. Both are valid options. I just wanted to bring up the other aspect, too.

**Comment by mstreit** [comment]
OK. If we remove the single bar from the vis option, it also means that the column cannot be combined/stacked with other numerical columns.

**Comment by sgratzl** [comment]
yes-ish. since it is based on the projection of 1D to 0D as mentioned before.

**Comment by alexsb** [comment]
I don't agree. Even if you have a projection into a lower space, you represent an aggregate value in some way. That aggregate has uncertainty and variability associated with it, so the within-the-bar bias still applies. 

See http://www.tandfonline.com/doi/pdf/10.1080/00031305.2016.1141706 

I think for stacking aggregates, we should think of something fancier?

**Comment by mstreit** [comment]
I get your point, but in Ordino users heavily use the stacking of columns where at least one is an aggregate.
Any ideas how 'something fancier' could look like?

**Comment by alexsb** [comment]
Something like this: 

![image](https://user-images.githubusercontent.com/2039375/31736815-ff0fa542-b402-11e7-9cbd-7680ce98dcd3.png)

Basics of a box plot, the darker areas show the possible positions of the mean for B and C. 

Or this: 

![image](https://user-images.githubusercontent.com/2039375/31736849-1c049126-b403-11e7-9d4e-85e8fe270db6.png)

The black violin plots are the distribution of only that variable, the red ones show cumulative uncertainty.

**Comment by sgratzl** [comment]
-> should be moved to #201

**Comment by mstreit** [comment]
solved with #362 and #401.

![image](https://user-images.githubusercontent.com/4129755/31944861-c5c2bc96-b8cd-11e7-9506-4597da549a36.png)
