### ISSUE TITLE
Add dot and/or line plot for numerical columns

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#387]
We should add a dot or a circle to represent numerical values: 

![image](https://user-images.githubusercontent.com/2039375/31679188-8f6d9d78-b32d-11e7-860d-d6cfa8b1869a.png)

We could also use just a vertical line | 

This also works well for grouping, especially with transparency and some jitter: 

![image](https://user-images.githubusercontent.com/2039375/31679230-bad58368-b32d-11e7-89ad-3c991102d7b9.png)

**Comment by sgratzl** [comment]
1. single numerical vis -> y pos = center
2. multi numerical vis / aggregate numerical vis / aggreate multi number vis -> y pos random

opacity: 0.7
radius: 2px

lod
 * high
 * low? height = 100%, y=0

**Comment by sgratzl** [comment]
![2017-11-17 16_17_42-taggle - aids](https://user-images.githubusercontent.com/4129778/32954569-c811b3fa-cbb3-11e7-9f68-0efd1eaaafae.png)
![2017-11-17 16_17_26-taggle - aids](https://user-images.githubusercontent.com/4129778/32954570-c830f382-cbb3-11e7-9b67-8d94c53e1435.png)

![image](https://user-images.githubusercontent.com/4129778/32954576-d2450af2-cbb3-11e7-8aa0-9ddcf18ed132.png)

**Comment by mstreit** [comment]
nice!
