### ISSUE TITLE
how to stratify the table by the cross product of multiple categorical attributes?

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#393]
This was possible in Taggle 1 and according to @sgratzl it should also be possible in Taggle2. However, what does a user need to do to achieve this?

**Comment by sgratzl** [comment]
what should the user need to do?

**Comment by mstreit** [comment]
I am not sure if I understand your question.

The user should be able to stratify by the combination of two categorical attributes. At the moment, it's only stratified by the single categorical attribute for which the user clicks on the stratify icon.

**Comment by sgratzl** [comment]
I know the goal but I don't know the desired workflow how the user should be able to do that

**Comment by mstreit** [comment]
I think the most intuitive approach is to stratify by the groups that the user visually sees. 
That means if the user stratifies the attribute that is at the top of the hierarchy, it will just stratify by the single attribute. If the attribute is second in the sorting hierarchy, it will take the combination of the top categorical attribute and the second one (where the user clicked the stratify icon). I think this is also the behavior we had in the original taggle.

**Comment by sgratzl** [comment]
currently already implemented approach: 

![multi_stratify](https://user-images.githubusercontent.com/4129778/31937153-e87e5584-b8b3-11e7-9a96-0c5bfa07ce40.gif)

alternative workflow:

![multi_stratify2](https://user-images.githubusercontent.com/4129778/31937154-e899d2c8-b8b3-11e7-98ae-6c56c83c2e50.gif)

**Comment by mstreit** [comment]
related to #420

**Comment by sgratzl** [comment]
see also #strat
