### ISSUE TITLE
Add summary histogram to matrix column 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#397]
Similar to number columns a histogram should be shown in the header of a matrix column.

![image](https://user-images.githubusercontent.com/5851088/31828087-9e0238d8-b5b9-11e7-8e82-ed2130cb0354.png)

**Comment by mstreit** [comment]
fixed in latest lineup.js 3.0 version
see demo https://lineup.js.org/app/#soccer

![image](https://user-images.githubusercontent.com/4129755/40548406-ea64e1e6-6034-11e8-9a06-f833bd26a91a.png)
