### ISSUE TITLE
Changing column order of a stratified column loses aggregation

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#399]
### Steps to reproduce

1. Stratify a column
2. Aggregate some groups
3. Drag and drop the stratified columns to a different position 

![reorder-columns-unaggregate](https://user-images.githubusercontent.com/5851088/31828656-23312810-b5bb-11e7-873f-a0ead5b06279.gif)

### Observed behavior
The column is not stratified anymore and the aggregations are lost

### Expected behavior
* The column should remain stratified
* The aggregated groups should remain aggregated

**Comment by mstreit** [comment]
related to #400

**Comment by thinkh** [comment]
Fixed with last PR #430.

![remain_stratified](https://user-images.githubusercontent.com/5851088/32663806-8b8ce9a6-c62f-11e7-89aa-8e0e531b817d.gif)
