### ISSUE TITLE
Create stacked bar renderer for aggregated groups of a categorical column

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#403]
It should be possible to select a stacked bar visualization for aggregated groups for a categorical column.

The implementation can be based on the histogram and "just be rotated".

![image](https://user-images.githubusercontent.com/5851088/31829988-30ab21b8-b5bf-11e7-9f3f-eb187a874b9b.png)

Note: The total width corresponds to the maximum number of elements (similar to the histogram).

**Comment by sgratzl** [comment]
> Note: The total width corresponds to the maximum number of elements (similar to the histogram).

in the histogram case, the global top histogram is used as a reference. Thus otherwise a two pass rendering would be needed. First, compute the histograms of all groups, Second, render based on the maximal one. However, this approach doesn't fit at all to the current rendering strategy and would take a lot of time.

**Comment by mstreit** [comment]
what is the problem with taking the global top histogram as a reference?

**Comment by sgratzl** [comment]
I don't know whether it is the desired behavior. Cause it means that 100% = all items not the maximal group size

**Comment by mstreit** [comment]
it means that small groups will show almost no stacked bars. I guess that's the desired behavior.
it basically looks the 'most frequent' encoding except that it works also for groups that contain items from more than one category.

**Comment by zichner** [comment]
> > Note: The total width corresponds to the maximum number of elements (similar to the histogram).
>
> in the histogram case, the global top histogram is used as a reference. Thus otherwise a two pass rendering would be needed. First, compute the histograms of all groups, Second, render based on the maximal one. However, this approach doesn't fit at all to the current rendering strategy and would take a lot of time.

Is a two pass rendering really needed in this case? If I understand correctly, the size of each bar would only depend on the total number of elements in the group and not on the size of any of the other bars.

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/33392569-c028c0e2-d53c-11e7-9c8a-ddaae3f11c0e.png)
