### ISSUE TITLE
Add button to collapse summary, labels and scales of column header

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#404]
Since the header has summary visualization and is growing with scales (#342), labels (#321, #335, #381, #382) we should add a button to collapse the header and hide these labels and visualizations on demand.

In the simplest case we can add toggle buttons to the sidepanel or configuration/options menu. That would look similar like [datacomb](http://www.bytemuse.com/datacomb/demo/).

![image](https://user-images.githubusercontent.com/5851088/31830812-a3c2c244-b5c1-11e7-9e57-f62d5218002f.png)

Alternatively,  we can integrate something like the aggregation arrow next to the header (might be confusing though).

![image](https://user-images.githubusercontent.com/5851088/31830936-09a44ba0-b5c2-11e7-85e7-b709d8a97c50.png)

**Comment by mstreit** [comment]
won't fix.
