### ISSUE TITLE
hide selected row border?

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#406]
The selection border introduces quite some visual clutter if multiple elements are selected. How about turning off the border? When selecting an item, it would still be obvious because the checkbox in the selection column is ticket. To make this more clear, we could set the color of the selected boxes to orange.

Opinions?

![image](https://user-images.githubusercontent.com/4129755/31937617-5c7ff612-b8b5-11e7-89fa-a6ff40aafbb1.png)

**Comment by sgratzl** [comment]
the selection column is optional + doesn't work in "overview" mode

**Comment by mstreit** [comment]
aha, yes. and the border is indeed helpful to see which cells in the different columns belong to selected items.

![image](https://user-images.githubusercontent.com/4129755/31937763-c01c2e98-b8b5-11e7-961c-358b4838d024.png)
