### ISSUE TITLE
ToolTip on hover in the table view in the whole area of the bar

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#408]
Currently the Tooltip appears only when hovering over the actual colored rectangle in histogram:

![01tag](https://user-images.githubusercontent.com/7511570/31951180-ab307f20-b8dd-11e7-880d-899f5114bc64.jpg)

I would expect the ToolTip to appear even in the area that is dedicated to the bar, like here in the sketch below. It is highly useful to get the data when the bar is so small you cannot even see it...

![02tag](https://user-images.githubusercontent.com/7511570/31951280-ef997bf8-b8dd-11e7-8cb7-1e5654063107.jpg)

**Comment by mijar** [comment]
I would say it's more related to usability :-) 
the blue rectangle is just the definition of area that should be covered by tooltip, but it should not be included in the ui

**Comment by mstreit** [comment]
OK, I've removed the aesthetics label ;)

Isn't it the default in many tools that the user only gets tooltips for bars (or other marks) when directly hovering over the element (and not the virtual maximum extent of the element)?

**Comment by mijar** [comment]
To be honest I don't know now, but it always irritates me when I want to know either an additional information or as here a value of some element, and it is just too small to make it work. Maybe it does not have to be a maximum extent, but at least a minimum height should be set to avoid this tackling with precision...
