### ISSUE TITLE
animation looks suboptimal for multi-item brush

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#409]
* Release number or git hash: taggle branch
* Web browser version and OS: chrome

### Steps to reproduce
1. switch to overview
2. brush multiple-items

### Observed behavior
* It seems that the items change the order during the transition.

### Expected behavior
* Just make items bigger (no order change).

**Comment by sgratzl** [comment]
screencapture please

**Comment by mstreit** [comment]
![image](https://user-images.githubusercontent.com/4129755/32037000-54f288be-ba23-11e7-8730-02b6f575b9a5.png)

**Comment by mstreit** [comment]
![video](https://user-images.githubusercontent.com/4129755/32037473-b3f4d932-ba25-11e7-892e-3d216a1df6d9.gif)

**Comment by mstreit** [comment]
The size gets initially smaller in height than the state before the animation. Also the brush indicator during the brush operation is not where the mouse is (the vertical orange line is not where I expect it to be).

**Comment by sgratzl** [comment]
please test again with the latest version

**Comment by mstreit** [comment]
seems to be still the same. I've tested it in the overview with the latest local version.

**Comment by sgratzl** [comment]
did you update the lineupengine, too?

**Comment by mstreit** [comment]
I just ran `git update` and `npm update`. But I am in `origin/taggle`

**Comment by mstreit** [comment]
I will switch to `develop` and test again.

**Comment by mstreit** [comment]
no
