### ISSUE TITLE
hierarchical sorting broken?

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#411]
* Release number or git hash: taggle branch
* Web browser version and OS: chrome

### Steps to reproduce
* sorted hierarchically by:
1) Continent
2) Human dev index
3) Ppl knowing they...

### Observed behavior
![image](https://user-images.githubusercontent.com/4129755/32020946-234554a0-b9d2-11e7-9ea9-31e631190e32.png)
 Ppl knowing they... should be sorted on level 3. This is not the case - see screenshot.

### Expected behavior
Proper hierarchical sorting.

**Comment by sgratzl** [comment]
part of https://github.com/Caleydo/lineup/commit/acd37a2add00e4c2381ab9e3784542afda754e39
