### ISSUE TITLE
aggregate all groups by default?

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#415]
@sgratzl commented on [Fri Sep 29 2017](https://github.com/Caleydo/taggle/issues/122)

when the user stratifies by a column, should we aggregate all groups by default?

see also #88 

---

@mstreit commented on [Fri Sep 29 2017](https://github.com/Caleydo/taggle/issues/122#issuecomment-333069278)

I would not do this in the public demos where the dataset is small enough to show the data without aggregation. But in Ordino, where we run into scalability issues in the overview mode, it's definitely the way to go. The user can then on-demand de-aggregate groups of interest.

---

@sgratzl commented on [Fri Sep 29 2017](https://github.com/Caleydo/taggle/issues/122#issuecomment-333071944)

so essentially: data size based decision

---

@mstreit commented on [Tue Oct 24 2017](https://github.com/Caleydo/taggle/issues/122#issuecomment-338983183)

aggregating the groups by default solves the immediate scalability issue. however, as mentioned by @zichner, it does not solve the problem that a user wants to see an initial overview before stratifying the table.

**Comment by mstreit** [comment]
we decided to not do this.
