### ISSUE TITLE
create a vertically stacked renderer

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#417]
like a nested one but instead shows it vertically stacked. e.g. if two bars are included show the two bars on top of each other in a single row. 

-> easier with higher row height.

**Comment by sgratzl** [comment]
default for min, max combiner

**Comment by sgratzl** [comment]
vis name: "Interleaved"

**Comment by sgratzl** [comment]
in addition add `data-primary=p` for the primary one, e.g .in min/max one

**Comment by thinkh** [comment]
Done with PR #433.

![interleaving](https://user-images.githubusercontent.com/5851088/32716699-3f0466d4-c857-11e7-95b8-7582e9fd3599.gif)


> in addition add `data-primary=p` for the primary one, e.g .in min/max one
@sgratzl If this is still on your agenda please extract into a separate issue.
