### ISSUE TITLE
More intuitive hierarchical stratification behavior

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#420]
Problem:
Stratifying by an attribute that is not on top of the hierarchy is very unintuitive:
E.g., I wanted to **sort first by Continent** and second by **Human devel. index** and **stratify by Human devel. index**. However, clicking the stratification button moves the attribute on top of the hierarchy and replaces the previously set stratification, which seems confusing, so to achieve this I had to: 1)Stratify by Human devel. index (Which moved to the top of the sorting hierarchy and 2)Drag the Continent tab in the filter view to the first position
![image](https://user-images.githubusercontent.com/8986080/32614850-70669fa8-c56e-11e7-933c-9c42781ebfda.png)

Suggested behavior:
Allow the user to select multiple hierarchical stratificators (stratifying attributes):
1) If no stratification is active, clicking the stratification button moves the attribute to the top of the sorting hierarchy and stratifies the data by that attribute (as it does right now).
2) If some stratification is set, clicking the stratification button will move the attribute in the sorting hierarchy to the position behind the already set stratificator/s. (E.g., If I first stratify by Continent and then by Human devel. index, I will achieve the state on the image).

**Comment by katush** [comment]
Reordering the selected stratification attributes should also be possible.

**Comment by katush** [comment]
Reordering the selected stratification attributes by dragging should also be possible.

**Comment by mstreit** [comment]
@sgratzl 
yes, that would be the consequence. you can still click the second one first (see that it's stratified by both) and then deselect the first one (only the second one remains stratified then).

any concerns?

**Comment by katush** [comment]
I don't think it would be such a problem if it was consistent with sorting behavior either:

- when  I click on the stratify icon it will be the primary one and the previous one will be the 2nd (but still applied)
 This is not happenning now either.

**Comment by sgratzl** [comment]
use same logic as in the sorting -> last one clicked = primary, previous one = secondary

**Comment by thinkh** [comment]
Fixed with last PR #431. If you want to change the behavior or have any other bugs please open a new issue.
