### ISSUE TITLE
Restore from Gist broken

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#429]
* Release number or git hash: deployed
* Web browser version and OS: chrome

### Steps to reproduce

1. save to gist
2. take link and past it in second browser window

### Observed behavior
* Only one item is contained in the restored table.

### Expected behavior
* Same items as in stored table. 

![image](https://user-images.githubusercontent.com/4129755/32654125-69a002d0-c60a-11e7-913b-0cd9f56b15c4.png)

**Comment by sgratzl** [comment]
Issue moved to [Caleydo/lineup #18](https://github.com/Caleydo/lineup/issues/18) via [**ZenHub**](https://www.zenhub.com/)
