### ISSUE TITLE
Dual behavior of histogram

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#432]
Initially, clicking on histogram bars removes the represented category.
However, once we filter out everything but one category, it begins toggling the selection between the clicked category and all categories. I.e., clicking on histogram bar removes all other bars or adds all bars.
I also don't like, that once you remove a bar, you cannot add it again (e.g., by clicking on the space where it should be).
![histogram](https://user-images.githubusercontent.com/8986080/32658210-321b1db8-c619-11e7-9758-376d092f6901.gif)

**Comment by mstreit** [comment]
I think the second issue you describe is the same problem as described in #408.

**Comment by katush** [comment]
It's related, yes - the whole area of the bar should be interactive.

**Comment by sgratzl** [comment]
now possible to filter out all categories, rest is in the other referenced issue
