### ISSUE TITLE
Selected column color is not reflected in side panel

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#440]
**Steps to reproduce**

1. Select a different color for numerical column

**Observed Behavior**

- The column color is reflected in the column histogram and bars, but not not in the histogram of the side panel.

![color-side-panel](https://user-images.githubusercontent.com/5851088/32717363-b20f4f70-c859-11e7-814c-5e167e29e2cb.gif)

**Expected Behavior**

The histogram in the side panel should have the same selected color and match with the column.

@sgratzl I assume that an event is missing at that point. However, I couldn't figure out which one is responsible here.

**Comment by sgratzl** [comment]
possible fix in https://github.com/Caleydo/lineupjs/commit/0d6390ed6a6c0a31327ad34ffe9cf78f256deceb

**Comment by thinkh** [comment]
Thanks. The fix works in my tests.
