### ISSUE TITLE
Improve appearance of interleaved box plot renderer 

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#445]
* Release number or git hash: develop
* Web browser version and OS: chrome

### Steps to reproduce
1. add max/min/mean column
2. drag two numerical columns onto the combined column
3. group by some categorical attribute
4. aggregate one of the groups

### Observed behavior
![image](https://user-images.githubusercontent.com/4129755/32734509-89f5256c-c892-11e7-8d88-8cf20a3ec4ba.png)

### Expected behavior
* interleaved box plots with proper height and colors that correspond to the different attributes

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32945858-528d0cba-cb95-11e7-8a55-31675a62a5aa.png)
