### ISSUE TITLE
Extend "Sort Group by ..." by other criteria (min, max, ...)

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#448]
At the moment groups can only be sorted by median (see https://github.com/Caleydo/lineupjs/issues/427). 

![image](https://user-images.githubusercontent.com/5851088/32736946-07491252-c899-11e7-9ab1-cfa2a2f5ad3a.png)

**Expected**

Offer different search criteria, as already implemented for numerical columns/box plot.

![image](https://user-images.githubusercontent.com/5851088/32736992-2c445152-c899-11e7-8d83-a4130ad48adf.png)

**Comment by mstreit** [comment]
Sort by number of items would also be useful.

**Comment by sgratzl** [comment]
> Sort by number of items would also be useful.

but that has nothing to do with a specific column but with the group itself

**Comment by mstreit** [comment]
I don't get your point.
As a user if want to sort by groups (not the items within groups) by statistical measures but also by the number of items within the group (i.e., size of groups).

**Comment by sgratzl** [comment]
my point is that "sort by number of element in the group" is not specific to a specific column. e.g. it has nothing to do with a number column, since it doesn't depends on the actual values within the group. 

see also the discussion about introducing a group column. sort groups by name and by count are things I would expect in such a column

**Comment by mstreit** [comment]
aha, hm. maybe a group dedicated group column as suggested by @alexsb is really a good idea :)

**Comment by sgratzl** [comment]
another somehow logical point would be aggregate column, i.e. where you collapse items to a group

**Comment by mstreit** [comment]
yes

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32958048-988673be-cbbd-11e7-8c85-bfb5793e5798.png)
