### ISSUE TITLE
Wrong scales after stratifying matrix columns

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#452]
* Release number or git hash: 
* Web browser version and OS: 

### Steps to reproduce
1. Stratify matrix by decade

### Observed behavior
All three groups show scales from 1990 to 20XX. 
![image](https://user-images.githubusercontent.com/4129755/32789195-844ff7da-c95b-11e7-9d8a-a48e9bd0650c.png)

### Expected behavior
* I would expect that the scales fit to the stratified data subsets.

**Comment by sgratzl** [comment]
actually part of lineup repo: 

![image](https://user-images.githubusercontent.com/4129778/32947359-c58db0b0-cb9b-11e7-9357-060b86ad293e.png)
