### ISSUE TITLE
"Shifted most frequent category" visualization broken

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#453]
* Release number or git hash: develop
* Web browser version and OS: chrome

### Steps to reproduce
1. Stratify by categorical attribute
2. Aggregate groups

### Observed behavior
![image](https://user-images.githubusercontent.com/4129755/32789693-c2c25430-c95c-11e7-926a-6a94c8a69569.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/4129755/32789657-adf4337a-c95c-11e7-9eec-99a8c94150c2.png)

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32947771-f448512a-cb9c-11e7-8938-b66e0f065805.png)
