### ISSUE TITLE
Box Plots treat NaNs as 0s

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#455]
Example: 

![image](https://user-images.githubusercontent.com/2039375/32852346-d919e5a2-c9f4-11e7-8715-37bc7b541f25.png)

### Steps to reproduce

1. aggregate by human development index,

### Observed behavior
 * look at the ppl know they have HIV in the very high class, only a few countries have entries but those that have, have a pretty high percentage
 * but the median is still set as 0

### Expected behavior
* NaNs shouldn't influence the calculation of any statistics.

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32952576-fbf899d2-cbad-11e7-8a8a-cdb9f4f8dd88.png)
