### ISSUE TITLE
Different mapping in Brightness and Heatmap

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#456]
I noticed we have different way of using brightness in our visualizations: Brightness - Highest value = Highest brightness (e.g. 0 = black, 100 = white), Heatmap Highest value = Lowest brightness (e.g. 0 = white, 100 = black), its confusing... I think we should stick to one of them (for me the second option is more intuitive.
![image](https://user-images.githubusercontent.com/8986080/32886174-26056fdc-cac0-11e7-8b88-6d8e155ccc5f.png)

**Comment by mstreit** [comment]
good point. it should definitely by consistent. to me, min=white & max=black is more intuitive.

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32946790-396e258a-cb99-11e7-8333-fa9034b9e3ed.png)
