### ISSUE TITLE
Add histogram visualization for Matrix rows

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#457]
We can display each matrix row in histogram form as a way of column aggregation.

![image](https://user-images.githubusercontent.com/8986080/32887351-e37d5aae-cac3-11e7-98b7-2ed87eafe878.png)

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/32952371-5f2f7da0-cbad-11e7-8e07-b4e9eccedc79.png)
