### ISSUE TITLE
Remove Bar and proportional symbol from Matrix

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#458]
Should we remove the Bar and Proportional symbol visualizations for matrix rows from the demo, since we claim we deliberately do not offer them?
"Wdeliberately do not offer visualizations that we consider as suboptimal visual encod-ings. An average bar, for instance, is not a suitable visualization for an aggregated vector."

**Comment by mstreit** [comment]
I agree that it does not make sense for median/mean/max/min. However, if the aggregation functions would be sum of all items (which is not implemented at the moment), then a bar and prop symbol encoding is definitely useful.
(This came up now when I tried to come up with our cancer case study.)
