### ISSUE TITLE
Apply filters to all visible snapshots

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#461]
at the moment filters set in the side panel are only applied to the primary ranking

![image](https://user-images.githubusercontent.com/4129755/32950481-c3e3c38e-cba6-11e7-9d46-db36ef3cda48.png)

**Comment by sgratzl** [comment]
I enabled it for the lineup but but not in general, since you might wanna have cases in which you use different filter settings

**Comment by mstreit** [comment]
OK (I need it for the Taggle cancer case study).

**Comment by sgratzl** [comment]
> OK (I need it for the Taggle cancer case study).

as I said I enabled it for the lineup application but that doesn't include the tdp version automatically.

**Comment by mstreit** [comment]
OK, then please also enable it for TDP.
