### ISSUE TITLE
create canvas version of Heatmap numbers renderer

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#462]
then we have at least just one DOM element for each row instead of the number of columns

**Comment by sgratzl** [comment]
alternative try out a fancy gradient background

**Comment by thinkh** [comment]
LineUp v4.0.0-alpha.8 uses the canvas element to render the heatmap.

![image](https://user-images.githubusercontent.com/5851088/49026578-7f706800-f19e-11e8-8fe9-f03d1fc00d5d.png)
