### ISSUE TITLE
group selection status not in sync with 'select all'

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#463]
* Release number or git hash: develop
* Web browser version and OS: chrome

### Steps to reproduce
1. stratify by some attribute
2. aggregate first group
3. checking 'select all' checkbox

### Observed behavior
* Group is unaffected by select all status (out of sync)

### Expected behavior
* Checking 'select all' will select all groups and items

![image](https://user-images.githubusercontent.com/4129755/32955472-5f23346a-cbb6-11e7-9ed3-bf52270310a4.png)

**Comment by sgratzl** [comment]
![gif](https://user-images.githubusercontent.com/4129778/32958355-831ea8e2-cbbe-11e7-8c7a-fea1dc0aa5ff.gif)
