### ISSUE TITLE
Wrong order  in side panel after drag&drop

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#466]
Reordering in side panel: 
![dragdrop](https://user-images.githubusercontent.com/8986080/32995809-2e02765a-cd7a-11e7-8fec-103aafbe6efe.gif)
Steps to reproduce:
Load Taggle.
Drag and drop Discriminatory attitude scale to 5th position.
Expected behavior:
Discriminatory attitude scale would be dropped to 5th position.
Observed behavior:
Discriminatory attitude scale appeared at 2nd position.
Possible cause:
After playing with this a bit, it seems that the dragged item is always marked as "the next one" (in this case 2nd) in sorting hierarchy and is dropped at the appropriate position. If I e.g. set Continent as 1st and Development index as 2nd in the hierarchy and then Drag and drop Discriminatory attitude scale to 5th position it will be marked as 3rd in the sorting hierarchy and dragged at 3rd position.

Web browser version and OS: chrome 62 @ Windows 10
Observed on the current daily build

**Comment by sgratzl** [comment]
closing in favor of #467 since it is part of the problem
