### ISSUE TITLE
Sorting hierarchy should reflect stratification hierarchy

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#467]
These three things should be in sync:

- Sorting hierarchy
- Stratification hierarchy (i.e., if one column is on top of stratification hierarchy, it should also be on top of sorting hierarchy)
- Order in the filter view

So nothing like this happens (notice the numbers denoting the sorting order):
![image](https://user-images.githubusercontent.com/8986080/32996038-9cf37656-cd7d-11e7-89ba-89a4ae7f211e.png)
reproduce:

- Sort by Ppl Knowing.
- Sort by Human dev...
- Sort by Continent
- Stratify by Human dev...

What I would expect (and also what the table reflected) is this (except for the A-Z/Z-a order, but that's separate issue):

![image](https://user-images.githubusercontent.com/8986080/32996139-29edfea4-cd7f-11e7-95a0-1b66b76361d4.png)

----

Other confusing examples where numbering does not make much sense:
![image](https://user-images.githubusercontent.com/8986080/32996113-bfb64fdc-cd7e-11e7-9d30-3cf122136fb4.png).
![image](https://user-images.githubusercontent.com/8986080/32996001-144634a6-cd7d-11e7-8aa5-8f9bb36f38d9.png)
![image](https://user-images.githubusercontent.com/8986080/32996398-6ff560ba-cd82-11e7-9284-579a51d15b16.png)
(In most cases I at least have an idea why it is so, but in this last one, there is no 2nd stratifier, just 1st and 3rd?)

Web browser version and OS: chrome 62 @ Windows 10
Observed on the current daily build.

**Comment by thinkh** [comment]
According to @sgratzl stratifications have a higher priority than sorting, i.e., that columns in the side panel are ordered like this:

1. Stratified columns
2. Sorted columns (without stratification)
3. Columns without stratification and sorting

Additionally the sorting and the stratification are handled separately and depend on the selection order by the user.

**Comment by katush** [comment]
Well in that case, there shouldn't be stratified&sorted columns? And how do you change the sorting order  A-Z/Z-A of stratifying columns, if stratification is above sorting? Having some columns only stratifying, some only sorting and some both is super confusing. As it is now, I really don't see logic in the above examples.

**Comment by katush** [comment]
Btw, I get the "logic"  that you describe and I think from implementation point of view that's more or les fine. My arguments for what I suggested above - i.e., stratifying columns are also (always) sorting columns, were: 
A) that's the order seen in the table
B) A-Z/Z-A ordering of stratifying columns could be intuitively changed that way
C) removing stratification can now mess up the the sorting on the table (in some cases unavoidable, but could be potentially less confusing)
Take the following example:

![stratification](https://user-images.githubusercontent.com/8986080/33016596-6c39d72c-cdef-11e7-8b5e-bed288a2698b.gif)

The behavior is technically correct, once I accepted that the columns at the top of the side panel are in fact at 6th and 7th place of sorting hierarchy (even though the the table is clearly ordered by them first, as a side effect of stratification), but I still don't like that by clicking that stratification button my table got completely reordered. Had i not carefully looked at the numbering in the side panel, I would expect the table to stay the same, just with les groups.

**Comment by mstreit** [comment]
One thing to consider: handling sorting and grouping independently does make a difference when stratifying a numerical column. (This was not possible with Taggle 1 and therefore we didn't discuss it back then).

**Comment by katush** [comment]
True, but if we keep it this way we should explain this thoroughly in paper. As I said, there are some counter intuitive consequences of this, so we should reason why we chose to do it this way. Section 6 doesn't describe this interaction design. And it might be worth to introduce the stratification first, as it is independent of and take priority over sorting.

**Comment by mstreit** [comment]
I agree that the current behavior can be hard to understand in some cases. 
The question is: Is there a consistent solution that works for all cases AND is intuitive? ;)

**Comment by katush** [comment]
Not that I can think of (unless we wan't to have some sort of duplicity to represent the the sorting and stratification order individually, but that would bring problems of it's own, so I don't think so). So the next question is, is it worth it to have one more feature at the price of unintuitive system?
Admittedly, now I see the numerical stratification as the only benefit of the current state, but there might be more benefits of current state or problems with my suggested approach that I am not thinking of...

**Comment by mstreit** [comment]
We already represent the sorting and stratification order independently via the numbers that we add to the icons. 
So this is what the user needs to understand:
- The sort and stratification hierarchies are independent
- The sort and stratification order is shown using the little numbers next to the icons
- The attributes in the panel are first ordered by the stratification hierarchy and then by the sort hierarchy.

**Comment by mstreit** [comment]
(btw, my feeling is that the nested stratifications in combination with multiple sortings is a power feature that only few users will ever experience).

**Comment by katush** [comment]
As long as we explain it thoroughly I am fine with it. I acknowledge that the nested stratifications are one of Taggle's most prominent features . 
But I am trying to represent the clueless user here (I think i am playing the clueless part rather well ;)) and here are some remarks of such user:
The way things work now, I don't really care obout this : _The attributes in the panel are first ordered by the stratification hierarchy and then by the sort hierarchy_. - The user does not really need to understand this. As the same order can occur in numerous different table configurations, it's not particularly informative, on the other hand relying on it for guidance can be confusing. The order of the attributes in the side panel is mainly useful in the way, that it groups the columns that "do something" at the top, but to understand what they do and what will happen if I click some buttons, I need to follow those small numbers or look at the table to see what is going on there. That being said, I think the ordering is still useful, just saying it is not particularly good for navigation in the sorting hierarchy. 
A side effect of independent sorting, the drag&drop operations become quite complex. In most cases I want to change the sorting or stratification of the columns that are at highest levels of those hierarchies. As a result, to understand what will happen if I drag a column at certain position, I need to think about the sorting numbering, the stratification numbering AND the position. And I will still get some confusing results:
If stratification has priority over sorting, why didn't the Human devlopment index stay at the top as a main stratification column? (I am not saying the set up was logical, but things like this occur, when you play with it a bit)
![sorting](https://user-images.githubusercontent.com/8986080/33020930-531c310c-ce00-11e7-8a99-ee346e6fe0ea.gif)

As I say, I don't mind the current approach, but it is not the most intuitive, thus we need to explain it properly. And make it consistent. Sorry for the long rant :)

**Comment by katush** [comment]
Side not for the UI- stratification takes priority -> switch the stratification and sorting icons in the side panel -> stratification first, than sorting.

**Comment by katush** [comment]
And fix numbering gaps in the hierarchies: 
![image](https://user-images.githubusercontent.com/8986080/33021214-5a9e3a78-ce01-11e7-8384-2e15f28ac2fa.png)

**Comment by katush** [comment]
Solution we agreed on with @mstreit:
For **categorical columns**, stratification also activates the the sorting and the sorting and stratification should be always at the same level in the respective hierarchies. I.e. 1. stratification column = 1. sorting column, 2. stratification column = 2. sorting column. (This reflects the order in the table -> consistent behavior for user).
**Numerical columns** will be treated the same as they are now.

**Comment by mstreit** [comment]
@sgratzl @thinkh, can you think of any cases where this behavior will lead to problems? the goal is that the order reflects what the user sees in the table.

**Comment by sgratzl** [comment]
current order in the side panel
 * stratified columns
 * sorted columns
 * remaining columns in order they appear in the table

what should be the target order + what should happen if the user drags a column within the side panel around.

**Comment by mstreit** [comment]
I think the order (stratified first, then sorted) is fine. The thing that needs to be changed is that stratified columns also automatically active the sorting icon (because this is what the user visually sees) - see last comment by @katush.

To come up with a final strategy what should happen after drag and drop in the side panel, I would need some examples. But the overall strategy should be that everything that categorical columns that are dragged *above* an already stratified column, should be stratified as well. If the user drags a numerical column above a stratified column, the stratified column will get unstratified. Hence, numerical columns act as a stratification breaker.

**Comment by sgratzl** [comment]
see related issue regarding drag&drop: 

what should happen if the user drags an arbitrary column at an other arbitrary other position
cases: the dragged column is: categorical, other
you drop before a column that is
 * a stratification criteria
 * a sorting criteria
 * none of it

**Comment by mstreit** [comment]
please make a concrete suggestion that tries to address the comments and also takes into account the considerations you have/had when implementing this.

**Comment by mstreit** [comment]
I think it does exactly what @katush described in her last comment. I didn't check the drag and drop behavior yet. But that's not too critical IMO.

**Comment by mstreit** [comment]
As the it remains undefined and unclear for the user what happens when changing the order of attributes in the side panel via drag and drop, we decided to turn off the feature. The user can influence the hierarchy by using the stratify & sort icons.
