### ISSUE TITLE
Toggling sorting button on stratification column does nothing

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#468]
When the column is set as stratifier, the sorting button is not working (although the icon is changing). 

Example:
Set some column as stratifying (e.g. Continent) & then try to change the order of that column, (e.g., continents) from A-Z to Z-A. When you first click the sort button it will A) Activate (go orange) as well as B) Switch the icon from A-Z to Z-A. One issue is that this, in my opinion, shouldn't happen in one click and the second issue is that table ordering stays A-Z. Subsequent toggling the sorting button will also have no effect on the table order. 

![image](https://user-images.githubusercontent.com/8986080/32996325-6a045234-cd81-11e7-8fae-4a3fb3cf42e9.png)

Web browser version and OS: chrome 62 @ Windows 10
Observed on the current daily build.

**Comment by sgratzl** [comment]
part of #467
