### ISSUE TITLE
Selection of multiple rows selects wrong rows 

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#469]
Quite often (I was unable to pinpoint any common prerequisites) the selection of multiple rows gets messed up and selects wrong rows.
In this particular case I
- Sorted by ppl knowing 
- Sorted by Human devel
- Sorted by Continent
- Stratified by Human Devel
- Stratified by Continent
and did the following selection:
![selection](https://user-images.githubusercontent.com/8986080/32996620-50a42fd6-cd85-11e7-8041-90f6631f8ce0.gif)

**Comment by sgratzl** [comment]
fixed in https://github.com/sgratzl/lineupengine/commit/7a39a1534d4fd6338bdcd072d124b307c4336437
