### ISSUE TITLE
Matrix stratification not restoring correctly from Gist

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#470]
Matrix stratification not restoring correctly from Gist. Although the stratification is there, each stratified column contains all the matrix data (1990-2015) instead of 1990-1999, 2000-2010, 2010-2015.
![image](https://user-images.githubusercontent.com/8986080/32998040-d5c34046-cd97-11e7-88fc-b59108f5b9d4.png)
There were also missing stratification data for matrices when I tried to re-add and re-stratify them:
![image](https://user-images.githubusercontent.com/8986080/32998227-7b10a132-cd99-11e7-8148-91c65eb1afb2.png)

**Comment by sgratzl** [comment]
Issue moved to [Caleydo/lineup #20](https://github.com/Caleydo/lineup/issues/20) via [**ZenHub**](https://www.zenhub.com/)
