### ISSUE TITLE
group name in overview mode

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#472]
similar to the aggregate icon that is shown for the first row of the group a similar thing for a group label would be nice. Cause currently the white space is useless without hover

![image](https://user-images.githubusercontent.com/4129778/33019329-1fc8d81a-cdfa-11e7-9431-5b5f6c6f7e7c.png)

**Comment by mstreit** [comment]
Given that the aggregated groups are now much easier to understand, it would also be very useful to have the same labels in the overview mode as well (see large green and red group blocks in screenshot). The strategy would be the same as for the new group columns: take the first atomic row of that group and add label.

![image](https://user-images.githubusercontent.com/4129755/33436691-0803e280-d5e6-11e7-8a4b-c6e204843413.png)

**Comment by sgratzl** [comment]
re group column: I agree. the rest, I don't since it doesn't have to be a stratification criteria.

**Comment by mstreit** [comment]
True. But if it is, we could show it. Or don't you have the information during rendering?

**Comment by mstreit** [comment]
I think that's all we need!
