### ISSUE TITLE
group column

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#473]
a dedicated column that provides meta data about a group. In the end a ordinal categorical column. 

 * categories = group name + color
 * value of a category = bar length = number of items within the group

Tho I don't know whether this column should be shown by default because on the item level there is no content. except, see #472

**Comment by mstreit** [comment]
yes, this meta column would also be very useful for filtering out small groups.

**Comment by sgratzl** [comment]
a dedicated group column exists that has two different sorting methods: name and count
