### ISSUE TITLE
sort group by min/max should highlight min/max outlier instead of whisker

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#474]
* Release number or git hash: daily
* Web browser version and OS: Chrome 

### Steps to reproduce
1. stratify by continent
2. aggregate all groups
3. urban population -> sort group by ...

### Observed behavior
* When selecting 'Sort group by -> Min" the highlight of the whisker is not the minimum/maximum anymore (since we changed the boxplot to show min/max outliers as dots.)

![image](https://user-images.githubusercontent.com/4129755/33030685-4725683e-ce1c-11e7-810d-6bd22b0fe5f6.png)

### Expected behavior
* Highlighting min/max dots - not the whiskers that do not correspond to min/max anymore

**Comment by sgratzl** [comment]
what if there are no outliers?

**Comment by mstreit** [comment]
then we can highlight the whiskers.

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/34382750-5ac631ae-eb11-11e7-9021-c07b821d8ee9.png)
