### ISSUE TITLE
remove redundant group labels and group size

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#475]
we currently show the group name and size in the label column. 
![image](https://user-images.githubusercontent.com/4129755/33031410-7e77e40e-ce1e-11e7-9a46-1b8ecea07327.png)

as this is redundant (mentioned by @alexsb multiple times), we can remove it in the label column and only show a few representatives.
the only problem is that the overview at the moment does not show group labels for stratified columns. however, this will be fixed in #472 and/or #473.

**Comment by zichner** [comment]
It might be good to have a separate `Group size` column. This would allow to sort the groups by size and maybe even to filter out groups (e.g., only keep groups of at least 10 entities).

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/33429314-96428c82-d5cc-11e7-9e68-2dea124e1a0d.png)

**Comment by mstreit** [comment]
Looks great! Also the possibility to sort it by group size is very useful.

![image](https://user-images.githubusercontent.com/4129755/33429613-e046205e-d5cd-11e7-960b-23cd8c636f29.png)

**Comment by mstreit** [comment]
We can now remove the group size from the stratifying categorical attribute.

![image](https://user-images.githubusercontent.com/4129755/33429666-0f8dbd54-d5ce-11e7-9e13-fc1eb5bd6577.png)

**Comment by mstreit** [comment]
This is so much better now!

![image](https://user-images.githubusercontent.com/4129755/33435991-fc484c58-d5e3-11e7-89ad-5c25ff41b624.png)

**Comment by thinkh** [comment]
Yes, it looks much better. I suggest to have a small padding left for categorical boxes.

**Comment by mstreit** [comment]
@thinkh, I agree. Can you please go ahead and take care of this?

Btw, in the future we could the font color depending on the background (switch between black and white).
