### ISSUE TITLE
better use of grouping hierarchy

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#476]
internally if multiple groupings are applied a tree like structure is created, 

see 

https://github.com/Caleydo/lineupjs/blob/97ee77c9b494d54d8327977e8090c6c7a528ae22/src/model/Group.ts#L5-L13

However, right now only the leaves are used. it is also not possible atm to aggregate a super group.

**Comment by thinkh** [comment]
It's not exactly clear what should be done here. I close this issue. You can re-open the issue if necessary.
