### ISSUE TITLE
wrong box plot whiskers?

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#477]
* Release number or git hash: latest
* Web browser version and OS: chrome

### Steps to reproduce
1. split numerical column
2. aggregate two groups

### Observed behavior
Non aggregated:
![image](https://user-images.githubusercontent.com/4129755/33079828-e0b7939a-ced6-11e7-9d7d-62af5019bd77.png)

Aggregated: 
![image](https://user-images.githubusercontent.com/4129755/33079680-84f6aa14-ced6-11e7-9c75-731f6752aad5.png)

The whiskers should not overlap. This came up when discussing the case study with Thomas.
This also demonstrates the problem:

![image](https://user-images.githubusercontent.com/4129755/33079927-1c6e03b0-ced7-11e7-8c6b-8141837a4c06.png)

### Expected behavior
The whisker of the lower part should not overlap with the whisker of the upper part if splitted. There seems to be something wrong in the calculation of the whiskers.

**Comment by sgratzl** [comment]
see https://github.com/Caleydo/lineupjs/pull/439

what is the right one?

**Comment by mstreit** [comment]
@thomas, what would you consider as the most commonly used way to calculate the whiskers? #439 summarizes how we do it atm)

**Comment by mstreit** [comment]
see also https://www.shmoop.com/basic-statistics-probability/box-whisker-plots.html

**Comment by zichner** [comment]
Currently the whiskers are computed like this:
```ts
const leftWhisker = Math.max(data.q1 - 1.5 * (data.q3 - data.q1), 0); 
const rightWhisker = Math.min(data.q3 + 1.5 * (data.q3 - data.q1), 1); 
```

However, they should be computed this way:
```ts
const leftWhisker = Math.max(data.q1 - 1.5 * (data.q3 - data.q1), Math.min(data)); 
const rightWhisker = Math.min(data.q3 + 1.5 * (data.q3 - data.q1), Math.max(data));
```
(NB: not sure if `Math.min(data)` and `Math.max(data)` is the right syntax to get the smallest/largest of all data points)

Explanation:
The length of the whiskers should be **at most** 1.5 times the interquartile range. But they are not allowed to extend beyond the actual data points.
