### ISSUE TITLE
add regular categorical group renderer to stratified column

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#480]
Steps to reproduce

 1. Open list of all cell lines
 1. Stratify by tumor type
 1. Collapse all tumor types

The values of the tumor type column are now for instance astrocytoma/glioblastoma (50) with some colored bar in the background (if there are enough samples in the group).
I would find it more intuitive if the information is displayed the same way as if the rows would not be collapsed, i.e., a colored square and then the tumor type. Especially in the case of multiple stratifying columns and many collapsed groups, this might help a lot to keep an overview. Furthermore, it reduces the amount of text shown.

**Comment by sgratzl** [comment]
still needed after  #403  ?

**Comment by mstreit** [comment]
I think that's addressed already with the latest changes..
