### ISSUE TITLE
Taggle: Remove labels of categorical column histogram if there are too many groups

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#482]
@zichner commented on [Tue Nov 28 2017](https://github.com/Caleydo/tdp_bi_bioinfodb/issues/762)

If there are many categories in a categorical column, the histogram labels cannot be read (not even the first few characters):

![screen shot 2017-11-28 at 09 48 19](https://user-images.githubusercontent.com/10066078/33310284-6024c39c-d421-11e7-9bea-dd58962a6dad.png)

In such a case, it would be better to hide the labels completely.

**Comment by sgratzl** [comment]
if there are too many categories, histograms doesn't make sense anymore. see also #341

**Comment by mstreit** [comment]
an option for the side panel would be to add horizontal scroll bars and assign a minimum width for bins.

**Comment by sgratzl** [comment]
but isn't the main goal of a histogram to see all items? + it doesn't scale very well either. e.g in the KUK case we have a hierarchy with 15k categories by default + it doesn't work in the inline header histogram

**Comment by mstreit** [comment]
the histogram in the side panel is also about filtering. and the hierarchical categorical is different.
if the histogram is scrollable you can still see everything - but just not at the same time (temporal partitioning) ;)

**Comment by mstreit** [comment]
done

![image](https://user-images.githubusercontent.com/4129755/34863429-a3f1f89e-f76f-11e7-8a1c-acf22bf142f4.png)

**Comment by thinkh** [comment]
@mstreit How is that fixed? I can't find any PR or commit that fixes this issue.

**Comment by mstreit** [comment]
maybe it's just fixed for ordino taggle. @sgratzl, please clarify.

**Comment by sgratzl** [comment]
see https://github.com/Caleydo/lineupjs/blob/develop/src/styles/header/_summary.scss#L6-L7
