### ISSUE TITLE
Wrong inequality signs in string description

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#484]
I stratified the countries by numerical attribute (e.g., Ppl knowing they have HIV) and aggregated the groups. The first group contains the greater values while the second contains lower values (see box plots), but the  inequality signs indicate the opposite:
![image](https://user-images.githubusercontent.com/8986080/33371988-c452ea16-d4fc-11e7-95e4-3fe4fdecbbe8.png)

**Comment by mstreit** [comment]
@katush, good catch!
