### ISSUE TITLE
Add padding to categorical renderer

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#487]
The labels are sticking at the left border...

![image](https://user-images.githubusercontent.com/4129755/33436034-294526ea-d5e4-11e7-9701-637db0cef514.png)

**Comment by sgratzl** [comment]
since it actually is a stacked bar, I wasn't able to easily fix with by adding a padding, cause padding would enforce a minimal width

**Comment by mstreit** [comment]
@thinkh, any idea how to address this? it still looks quite ugly.

![image](https://user-images.githubusercontent.com/4129755/34863460-d5d2ef76-f76f-11e7-9745-fc4db49f267b.png)

**Comment by thinkh** [comment]
Fix is available in PR #506.
