### ISSUE TITLE
Switch between light and dark font color for categorical renderer

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineupjs#489]
The category labels would be better readable, if we switch between white and dark based on the background color.

![image](https://user-images.githubusercontent.com/4129755/33436034-294526ea-d5e4-11e7-9701-637db0cef514.png)

This would be helpful:
- http://www.thesassway.com/intermediate/dynamically-change-text-color-based-on-its-background-with-sass
- https://css-tricks.com/reverse-text-color-mix-blend-mode/

However, I don't know if this is possible at all since we add the colors as inline style to the category `div`. But we can at least give a try and experiement.

**Comment by mstreit** [comment]
Thanks @thinkh.
Implementing this is not needed for the submission though.
