### ISSUE TITLE
Cannot open some of the aggregated groups after stratification 

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#490]
* Release number or git hash: latest local
* Web browser version and OS: chrome

### Steps to reproduce
I don't really know how to reproduce it. However, this behavior was also observed by @dfuchs1702 in the TourGuide instance.

![image](https://user-images.githubusercontent.com/4129755/33439907-e15ee7e8-d5ee-11e7-9a47-720841513dff.png)

### Observed behavior
* Aggregated groups cannot be opened by clicking on arrow.

**Comment by sgratzl** [comment]
invalid, since the underlying issue #485  was solved
