### ISSUE TITLE
Combining columns via drag and drop doesn't create nested column in data panel

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#493]
Combining columns via drag and drop doesn't create nested column in data panel:
It is possible to add empty nested/combined column via data selection panel  - in such case it will be also represented in data selection panel. However, when combining columns via drag and drop in table, no such representation appears in Data Panel. This should be consistent.
Also, some indication of attributes making up the combined column in data panel would be helpful (if more column combinations are in the table, it is impossible to tell, which one is which).

**Comment by mstreit** [comment]
as far as I can tell this works now in the new lineup.js 3.0 version

![image](https://user-images.githubusercontent.com/4129755/40552925-75902030-6041-11e8-9c53-189da914dc41.png)
