### ISSUE TITLE
Filter all checkbox in categorical column filter dialog exists but is invisible

### ISSUE THREAD

**Issue by mstreit** [Caleydo/lineupjs#494]
* Release number or git hash: deployed Taggle demo + Ordino Taggle
* Web browser version and OS: Chrome

### Steps to reproduce
1. Open filter dialog in categorical column

![image](https://user-images.githubusercontent.com/4129755/33612558-3fc4e0ee-d9d2-11e7-97ce-5411fa19b5b1.png)

### Observed behavior
* Checkbox invisible but appear when the user clicks the invisible box

### Expected behavior
* Visible checkbox

**Comment by sgratzl** [comment]
cannot reproduce: when I open the dialog all checkboxes are there

![image](https://user-images.githubusercontent.com/4129778/34381911-d812759c-eb0b-11e7-810b-c6fd39f44b39.png)

**Comment by mstreit** [comment]
the one on the left of the Category label is missing ('filter all').

**Comment by mstreit** [comment]
![image](https://user-images.githubusercontent.com/4129755/34382398-d666e13a-eb0e-11e7-8272-533dd24f5fc6.png)

**Comment by mstreit** [comment]
maybe we should add a dedicated 'Filter all' entry to the list. not sure if users get what the box next to the 'category' label does.
