### ISSUE TITLE
Taggle: keep column dialogs (Filter etc) open unless one clicks somewhere else

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#495]
@zichner commented on [Thu Dec 07 2017](https://github.com/Caleydo/tdp_bi_bioinfodb/issues/775)

At the moment, the column dialogs like `Filter` and `Sort by` are closed as soon as the mouse is a few pixels outside of the dialog. This can be very annoying because the dialogs often close unintentionally. Therefore, I prefer that one needs to click outside of the dialog in order to close it (or at least to move the mouse further away).

**Comment by sgratzl** [comment]
increased click region for now. Border indicates area. 

![image](https://user-images.githubusercontent.com/4129778/34381540-70ae328a-eb09-11e7-9015-a4db9a1aa02b.png)

**Comment by mstreit** [comment]
seems to be a good solution. re-open if it is not satisfactory.

**Comment by zichner** [comment]
I would increase the area even a bit more (maybe about double of what it is at the moment).
Furthermore, clicking anywhere outside of a dialog should also close it (if it is easy to implement).

(I do not have permission to re-open the issue)

**Comment by thinkh** [comment]
Done with https://github.com/Caleydo/lineupjs/pull/511.
