### ISSUE TITLE
Rename Distribution bar to Stacked bar

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#496]
Rename Distribution bar visualization fo aggregated categories to Stacked bar

**Comment by sgratzl** [comment]
but is is a distribution and not a pure stacking. the values among groups are not comparable, because the it is essentially a stacked histogram thus sum up to 100% = distribution

**Comment by mstreit** [comment]
a stacked bar that sums up to 100% is still a stacked bar. 
the stacked bar chart type refers to the representation and does not describe what the numbers are. a pie chart, for example, is also not a distribution chart.
