### ISSUE TITLE
Add brightness encoding to aggregated category matrix

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#497]
Add brightness encoding to aggregated category matrix so the brightness would encode frequency of categories: 
![image](https://user-images.githubusercontent.com/8986080/33885775-9766f5f4-df44-11e7-822e-be2cfb81a0c7.png)

**Comment by thinkh** [comment]
General feature -> moved to https://github.com/datavisyn/lineupjs/issues/115.
