### ISSUE TITLE
Filterboxes dont work correctly

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#499]
@NMO13 commented on [Thu Dec 14 2017](https://github.com/Caleydo/taggle/issues/146)

Create two numerical columns. Stack them. Go to "edit weights". Change the weights.

Expected: The weights should change independently.

Actual: Changing one weight also changes all other weights.

![20171213_195934](https://user-images.githubusercontent.com/3988444/33992603-93d0cd1c-e0d3-11e7-835d-e786413a8c00.gif)

**Comment by mstreit** [comment]
Occurs in ordino-taggle.caleydapp.org.

![image](https://user-images.githubusercontent.com/4129755/34382241-c54f9924-eb0d-11e7-8abb-beb29a2665a3.png)

**Comment by mstreit** [comment]
I was in the wrong issue. Thought you cannot reproduce this one..
