### ISSUE TITLE
demo/test.html fails with "Uncaught (in promise) TypeError: col.isMissing is not a function"

### ISSUE THREAD

**Issue by moritzschaefer** [Caleydo/lineupjs#504]
* master branch
* Arch Linux, Google Chrome

### Steps to reproduce

1. Compile as in described in the README
2. Go to demo/ folder, create a symblink to ../node_modules and ../build
3. Start a http server (python -m http.server), go to localhost:8000/test.html

### Observed behavior

![image](https://user-images.githubusercontent.com/2714540/34834817-4e6cdb72-f6f3-11e7-9b1b-979ae3043ae4.png)

Parts of the table are invisible or only visible while hovering. 

The developer console states 

    StackCellRenderer.ts:93 Uncaught (in promise) TypeError: col.isMissing is not a function
    at Object.renderer (StackCellRenderer.ts:93)
    at CanvasBodyRenderer.ts:147
    at Array.forEach (<anonymous>)
    at BodyCanvasRenderer.renderRow (CanvasBodyRenderer.ts:144)
    at CanvasBodyRenderer.ts:192
    at <anonymous>

30 while/times after loading and then again many times when interacting with the table 

![image](https://user-images.githubusercontent.com/2714540/34834872-7c32a06e-f6f3-11e7-8772-22875ccaeb96.png)

### Expected behavior
* No error in console
* Full visibility and interactibility of the lineup table

**Comment by thinkh** [comment]
@moritzschaefer Thanks for your issue. Can you please add which branch you were using in your tests?

**Comment by moritzschaefer** [comment]
Master branch

**Comment by thinkh** [comment]
I recommend to checkout and use [develop branch]. Please try the test there again.

**Comment by moritzschaefer** [comment]
In develop branch a file 'build/style.css' is missing. And it looks like this:

![image](https://user-images.githubusercontent.com/2714540/34880258-3167fc74-f7b0-11e7-8826-0743d4ff77cd.png)

**Comment by thinkh** [comment]
Please checkout the most recent LineUp version from https://github.com/datavisyn/lineupjs/. Thanks.
