### ISSUE TITLE
Value mapping (raw input to normalized output) does not work for raw matrix columns

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#520]
* Release number or git hash: dev

For normal numerical columns one can alter the mapping between raw input and bar length (e.g., inverting or log transform).
It would be great if that would also work for raw matrix columns.

**Comment by thinkh** [comment]
This feature is integrated in LineUp v4.0.0-alpha.8.

![image](https://user-images.githubusercontent.com/5851088/49028474-c82a2000-f1a2-11e8-85fe-b392b6645b09.png)
