### ISSUE TITLE
Taggle: add the size of the group indicator to the group label of unaggregated group

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#526]
Would it be possible to add the size of the group indicator to the group label of unaggregated group in the group column? Now it works only for the aggregated groups.

![image](https://user-images.githubusercontent.com/8986080/38500207-0c49d946-3c0a-11e8-922c-d923043c84a7.png)

**Comment by mstreit** [comment]
I agree, good point.

**Comment by mstreit** [comment]
That should also be the case for single stratifications:
![image](https://user-images.githubusercontent.com/4129755/38502225-2653cbf8-3c0f-11e8-90ea-433450165176.png)

**Comment by mstreit** [comment]
fixed in the lineup.js 3.0
![image](https://user-images.githubusercontent.com/4129755/40547066-3110ef12-6031-11e8-8dc1-fba311c15374.png)
https://lineup.js.org/app/#soccer

**Comment by mstreit** [comment]
As we will not fix issues in the outdated taggle version, I am closing this issue.
