### ISSUE TITLE
Taggle: the hidden columns can be seen behind the fixed label columns when using horizontal slider

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#527]
When using the horizontal slider in the window (if the columns do not fit the screen), the columns that should be hidden can be seen behind the fixed label columns. Watch the AIDS_Countries column below Botswana as well as in the header:
![slider](https://user-images.githubusercontent.com/8986080/38543010-ab229b36-3ca3-11e8-96e8-06ed0537a1f6.gif)

**Comment by mstreit** [comment]
seems to be fixed in latest lineup.js 3.0 version
