### ISSUE TITLE
Gist upload failure

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#528]
Uploading local dataset to gist failed:
Steps:
I loaded a csv dataset (https://www.kaggle.com/artimous/complete-fifa-2017-player-dataset-global/data) into taggle.caleydoapp.org and tried to save it to gist.
Error:
Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by mstreit** [comment]
won't fix in the old taggle version
https://github.com/datavisyn/lineup_app/issues/9
