### ISSUE TITLE
Taggle: The missing value filter overlaps with histogram labels in filter view

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#529]
The text  _Filter out X missing value rows_  does not fit on one line and thus overlaps with histogram labels in filter view. Moreover, it's not consistent, as for string it just states  _Filter out X missing values_ I suggest keeping the shorter version which would fix both issues. Alternatively increase  either the height of the filter blocks or set the fixed wider width of the whole filter view (for AIDS dataset the filter view is much wider so i am guessing it is adjusting to data).

Overlaps:
![image](https://user-images.githubusercontent.com/8986080/38928210-62bb6024-4308-11e8-9098-e7792f222686.png)

Changing width of filter view:
![width](https://user-images.githubusercontent.com/8986080/38928593-992818ea-4309-11e8-8f61-95cc5daaa203.gif)

**Comment by mstreit** [comment]
I agree. 'Filter X missing values' sounds good.

**Comment by mstreit** [comment]
Fixed in latest version.

![image](https://user-images.githubusercontent.com/4129755/40547318-e780f3d2-6031-11e8-9384-1cdc9c03176b.png)
