### ISSUE TITLE
Taggle-Soccer Dataset Histograms

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#530]
The histograms for 'current club' and 'nationality' attributes in soccer dataset are not working (neither in column header, nor in filter view).
At first I thought the bars are just too small, but that is not the case, the histogram is not there at all.

**Comment by katush** [comment]
The problem seems to be that if there are more that 50 categories (there are cca 170 clubs and over 200 nationalities) the histograms are not drawn even if the width of the column would allow it.

**Comment by mstreit** [comment]
you can change the type to text/string.

**Comment by katush** [comment]
@mstreit I would like to keep it as categorical columns, at least the club one - even if the histograms will are not shown, you can still group by them and see the color encoding, which is useful. I don't see why the histogram can't be shown when the width allows it.

**Comment by mstreit** [comment]
OK, whatever you think makes more sense for the user study story.
The color mapping obviously does not make any sense in this case.

**Comment by thinkh** [comment]
Another improvement/alternative would be to show the list of categories (similar to the filter) in the side panel, so that the user can directly filter some categories (see mockup).

![image](https://user-images.githubusercontent.com/5851088/39253580-77dfeb28-48a8-11e8-8125-fd7444c3a186.png)

**Comment by katush** [comment]
For now I changed it to string attribute, as it's better than no filtering at all and it shouldn't be a problem for the user study. I like Holger's suggestion though and opened an issue for this purpose https://github.com/Caleydo/lineupjs/issues/537
