### ISSUE TITLE
The header of a matrix column doesn't change correctly

### ISSUE THREAD

**Issue by NMO13** [Caleydo/lineupjs#531]
1. Click on games -> season
![image](https://user-images.githubusercontent.com/3988444/39252382-cfd5df84-48a5-11e8-94d9-759d238eb404.png)

Expected result: The header of the matrix column shouldn't change
Actual result: The header shows the first column of the matrix
![image](https://user-images.githubusercontent.com/3988444/39252446-f1eb192c-48a5-11e8-953e-804e058a7897.png)

**Comment by thinkh** [comment]
And when you split a combined column the numerical columns does not appear in the sidebar.

![taggle-split-combined-columns](https://user-images.githubusercontent.com/5851088/39252883-e7959ed8-48a6-11e8-9859-b9cfc64388c7.gif)

**Comment by thinkh** [comment]
This is fixed in LineUp v4.0.0-alpha.7.

![image](https://user-images.githubusercontent.com/5851088/49028592-06274400-f1a3-11e8-9b77-49ae0b15e5d5.png)
