### ISSUE TITLE
Rename "Stratify by..." so something more obvious

### ISSUE THREAD

**Issue by NMO13** [Caleydo/lineupjs#532]
Maybe the text "Stratify by..." is a bit misleading because its actual a decomposition of the matrix.
![image](https://user-images.githubusercontent.com/3988444/39252652-66c11f80-48a6-11e8-9d01-d36078d5a287.png)

Maybe it should be renamed "Decompose by..."

**Comment by mstreit** [comment]
Yes, the term stratify is not super intuitive. How about 'Split by...'?

**Comment by mstreit** [comment]
@thinkh will create a PR for this in the lineup.js version.
