### ISSUE TITLE
Filtering of categorical attributes with more than 50 categories

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#537]
If there are more than 50 categories for an attribute, the histograms are no longer shown and it is thus impossible to filter them - the side panel stays empty, which is really confusing. See issue https://github.com/Caleydo/lineupjs/issues/530 

@thinkh suggested suggested to show the list of categories (similar to the filter) in the side panel, so that the user can directly filter some categories (see mockup)
![image](https://user-images.githubusercontent.com/8986080/39704511-dd8bcb92-520b-11e8-9572-0ac4485016e2.png)

**Comment by thinkh** [comment]
General feature -> Moved to https://github.com/datavisyn/lineupjs/issues/113.
