### ISSUE TITLE
Search doesn't seem to work

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#538]
If I search for a soccer players name, nothing happens.

**Comment by mstreit** [comment]
Cannot reproduce. I tested it in Chrome and it works. What did you do exactly?

**Comment by mstreit** [comment]
@alexsb, please check in latest version if the search does what you expect
https://lineup.js.org/app/#soccer

**Comment by thinkh** [comment]
Closed. Please reopen again if necessary.
