### ISSUE TITLE
Loading when scrolling is irritating

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#539]
See: 

![may-17-2018 14-48-45](https://user-images.githubusercontent.com/2039375/40197436-72acfee4-59e1-11e8-83ee-183726772ed5.gif)

It takes a while to load in data as I scroll further. We should use a cashing strategy to remedy this; for example pre-cache 1 1/2 pages in each direction.

**Comment by mstreit** [comment]
I cannot reproduce this. Did you have a small internet connection? Can you try it with the demo version on lineup.js.org?

**Comment by thinkh** [comment]
I guess @alexsb is using the Firefox?

**Comment by mstreit** [comment]
@alexsb, please verify.

**Comment by mstreit** [comment]
OK, please re-open if you observe the issue again.
