### ISSUE TITLE
Legends missing for matrices

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#541]
What does dark mean? What does light mean?

![image](https://user-images.githubusercontent.com/2039375/40197804-7059cf22-59e2-11e8-8faa-0846d6f4afdf.png)

**Comment by mstreit** [comment]
good point. how about adding a legend to the corresponding side panel section?
(it's not a bug, rather a missing feature).

**Comment by thinkh** [comment]
General feature. Moved to https://github.com/datavisyn/lineupjs/issues/112.
