### ISSUE TITLE
better highlight that this repo is just a fork of datavisyn/lineupjs

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/lineupjs#549]
since we changed the root repo to https://github.com/datavisyn/lineupjs. it would be nice to highlight (e.g. in the repo header description line) that the latest stable version can be found at https://github.com/datavisyn/lineupjs and https://lineup.js.org

**Comment by thinkh** [comment]
Done. 
> Fork and custom implementation of LineUp Library for Visual Analysis of Multi-Attribute lineup.js.org
