### ISSUE TITLE
Cloning one column/one part of the stratified matrix doesn't work

### ISSUE THREAD

**Issue by katush** [Caleydo/lineupjs#556]
It seems that Cloning one column/one part of the stratified matrix doesn't work - the snapshot will appear without the cloned column.
Steps: Stratify goals by seasons and then clone season 15/16 column
Result: A snapshot of the table with Group Name, Rank and Player columns will appear, but the actual column with season 15/16 will be missing.

![image](https://user-images.githubusercontent.com/8986080/43267485-655fb85a-90ee-11e8-9b52-3186b19ba7e6.png)

**Comment by thinkh** [comment]
Moved to https://github.com/datavisyn/lineupjs/issues/49.
