### ISSUE TITLE
Should we be able to sort by an element that is part of a combiner? 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineupjs#69]
In LineUp.js you can sort by every colum, irrespective of whether it's part of a combiner. In LineUp original this is not possible. Instead clicking on a nested column changes the alignment of the stacked bar. 

My intuition says we should stick to the original LineUp behavior here.

**Comment by mstreit** [comment]
With the taggle updates, this is possible:
![image](https://user-images.githubusercontent.com/4129755/34864242-9810a71a-f773-11e7-839d-e4fad86ed12d.png)
